### ISSUE TITLE
Toast messages shows up twice (angular 2.4)

### ISSUE THREAD

**Issue by robinkedia** [Stabzs/Angular2-Toaster#100]
Hi - After I upgraded from Angular 2.0.0 to 2.4, I see the toast messages are appearing twice. 

 this._toasterService.popAsync(this.toastMsg.type, this.toastMsg.title, this.toastMsg.message);

Please advise. Thanks!

**Comment by Stabzs** [comment]
Hi, can you please create a quick plunker demonstrating the issue?  You can use http://plnkr.co/edit/hkENUhos6q9fhiOHprXO?p=preview as a baseline.

**Comment by robinkedia** [comment]
From our initial finding, we see if remove routerLinkActive="router-link-active" from html tag. The toast comes up only once else it fires twice. Will try my best to put plunker.

**Comment by Stabzs** [comment]
You should keep your container reference outside of any routing.

**Comment by robinkedia** [comment]
What if i have child routing (2 router outlet)

LayoutComponent Html
<routeroutlet>
<app>
    <toaster></toaster>
    <routeroutlet></routeroutlet>
</app>
</routeroutlet>

**Comment by Stabzs** [comment]
I'd have to see an isolated example in a plunker to say one way or the other.

**Comment by Stabzs** [comment]
Closing this issue as irreproducible.  If you are able to create a plunker reproducing the issue or you have further details, please add them to the issue and I will be happy to take a look.
