### ISSUE TITLE
Cannot set property 'toastId' of undefined

### ISSUE THREAD

**Issue by jasonspick** [Stabzs/Angular2-Toaster#103]
Getting this error when following these instructions: Getting Started with Default Configuration - Manual Component Inclusion.

I am importing:
`import { ToasterService } from 'angular2-toaster/angular2-toaster';`

setting up constructor:
`private toasterService: ToasterService;

    constructor(
        private http: Http,
        private authHttp: AuthHttp,
        private ts: ToasterService,
        private router: Router
    ) {
        this.toasterService = ts;
    }`

then calling pop:
`this.toasterService.pop(response.status, error.statusText, response.message);`

the container is in my app.component.html file:
`<toaster-container></toaster-container>`

Any thoughts on what I might be missing?

**Comment by Stabzs** [comment]
Hmm, this is a bit odd.  Can you possibly create a plunker demonstrating the problem?
