### ISSUE TITLE
Router Navigate after toaster closes

### ISSUE THREAD

**Issue by laura2489** [Stabzs/Angular2-Toaster#105]
I am trying to implement a router.navigate back to dashboard after an action is completed and only after the toaster closes. Can you please help me?

**Comment by Stabzs** [comment]
Would you be able to create a plunker of what you are trying to accomplish?  Currently there are no 'onClose' events fired, but that may be a reasonable addition.  Another option is to create a component and invoke a service or change state when that component in the toast itself is destroyed.
