### ISSUE TITLE
Update to Angular 4?

### ISSUE THREAD

**Issue by rolandoldengarm** [Stabzs/Angular2-Toaster#106]
Any plans to update dependencies to Angular 4?

**Comment by Stabzs** [comment]
Yes!  I wanted to wait until the dust settled on a full release version but this is a priority!

**Comment by tomalex0** [comment]
As angular 4 stable is release, would like to see with updated dependencies

**Comment by christiancoan** [comment]
As a quick fix, download the src folder and add to your project. Remove the spec files for now and change references. The project does work with angular 4, it just has peer dependencies through npm which prevents compilation on a production build.
