### ISSUE TITLE
No Directive annotation found on ToasterContainerComponen

### ISSUE THREAD

**Issue by jboesch0** [Stabzs/Angular2-Toaster#11]
Hi, got this error any idea ?

**Comment by mwoodsmall** [comment]
can you provide some more information?

possibly some sample code, or maybe a plunkr that reproduces this issue?

**Comment by Stabzs** [comment]
I suspect you are using webpack.  If you are, it would be related to this issue that I was unable to reproduce: https://github.com/Stabzs/Angular2-Toaster/issues/8

Most likely you are not including a required shim or polyfill that is needed when webpack generates your bundle.  

Please provide the smallest possible complete, working example that demonstrates the error.
