### ISSUE TITLE
Why is there no options for Type Customization as well as HTML custom template for Toast?

### ISSUE THREAD

**Issue by shivkumarganesh** [Stabzs/Angular2-Toaster#110]
I am using this plugin but am facing issues which are as follows:-

1. I did not find a way in which I can have my own icons for specific events
2. I wanted to know a way in which this plugin can take an HTML as an input and generate the template for the toast, i.e Custom Toast

**Comment by Stabzs** [comment]
I may be misunderstanding your questions, but unless I am, both of these particular issues are already solved and implemented within the library and can be customized to meet your needs.

1.  Yes, you can use your own icons by overriding either the `typeClasses` or the `iconClasses` for the toasterConfig, depending on how thoroughly you need to override the templates.  You can then use your own CSS and class definitions for each of the overrides.  You can see an example of this here: http://plnkr.co/edit/gZTxVXD8lN3fibqhDYod?p=preview 

2.  Yes, you can provide your own custom HTML by utilizing the `BodyOutputType.Component` type OR `BodyOutputType.TrustedHtml` if you only need to override simple layout behavior.  See https://github.com/Stabzs/Angular2-Toaster#body-output-type and http://plnkr.co/edit/Duc4JfIqsa4UnPRFq3pG?p=preview

If this isn't sufficiently clear, please let me know what you're looking for.
