### ISSUE TITLE
Webpack issue

### ISSUE THREAD

**Issue by c-saw** [Stabzs/Angular2-Toaster#115]
I get an error when building with Webpack:

ERROR in [at-loader] ./node_modules/angular2-notifications/src/simple-notifications/services/notifications.service.ts:51:72 
    TS7017: Element implicitly has an 'any' type because type 'Icons' has no index signature.

The way I fix it is to change line 51 in the notifications.service.ts from:

```
return this.set({title: title, content: content, type: type, icon: this.icons[type], override: override}, true);
```

to:

```
return this.set({title: title, content: content, type: type, icon: (<any>this.icons)[type], override: override}, true);
```

**Comment by Stabzs** [comment]
You've opened an issue on the wrong library.
