### ISSUE TITLE
error -    (SystemJS) Unexpected token <

### ISSUE THREAD

**Issue by subhani1249** [Stabzs/Angular2-Toaster#116]
hi,
I have tried to integrate Angular2-Toaster in my project, I am getting this error.
Can you please conform what is the issue ?

(index):19 Error: (SystemJS) Unexpected token <

When I start the app these 2 Toaster related files are loaded 
![image](https://user-images.githubusercontent.com/10893928/27214850-1fbf1058-528c-11e7-87dc-5dae630db5ac.png)

i am getting error in app.module.js where i have imported ToasterModule.
![image](https://user-images.githubusercontent.com/10893928/27214891-5b0a8412-528c-11e7-936b-b16117a05087.png)

**Comment by Stabzs** [comment]
There could be a number of missing dependencies. Could you please create a plunked that reproduces the issue?
