### ISSUE TITLE
Unable to insert linebreaks in Toaster Body

### ISSUE THREAD

**Issue by nic-ridder** [Stabzs/Angular2-Toaster#117]
Tried `\n`, `\n\n`, `\r\n`, and `<br /> `in the string of the toaster body and to no avail, I can not force a line break within the body of the toaster (easily).

Maybe having the option of using `<pre>` instead of `<div>` would address this?

**Comment by Stabzs** [comment]
You are most likely not using BodyOutputType.TrustedHtml

**Comment by nic-ridder** [comment]
That was exactly my issue.  Thought I searched the documentation thoroughly.  Thanks for pointing that out! 👍

**Comment by Stabzs** [comment]
@nic-ridder absolutely!  I'm glad to hear that it was that simple.
