### ISSUE TITLE
No dismiss option

### ISSUE THREAD

**Issue by saransh944** [Stabzs/Angular2-Toaster#119]
One issue with Angular2 Toaster is, it doesn't have a dismiss property or function. It should have a boolean property in the interface which can be triggered from a function. This would be helpful if somebody wants to dismiss the Toaster on route change, etc manually.

**Comment by Stabzs** [comment]
There is already an option for dismissing toasts, although it is not a "per toast flag" but rather the behavior is driven via `toasterService`.  

When you pop a toast, the toast instance is [returned ](https://github.com/Stabzs/Angular2-Toaster/blob/master/src/toaster.service.ts#L50).  

You can then invoke the [toasterService.clear](https://github.com/Stabzs/Angular2-Toaster/blob/master/src/toaster.service.ts#L80) function, passing in the `toastId` from your toast instance. This allows the toastContainer to properly tear down the toast instance, triggering the appropriate animations.

I've updated the [demo plunker](http://embed.plnkr.co/1POpuc1tDpxK7dw1BD5d/) to angular2-toaster@4.0.0, added animations, and I've added a very simple example that demonstrates this behavior.
