### ISSUE TITLE
ReferenceError: Can't find variable: exports - karma

### ISSUE THREAD

**Issue by mwoodsmall** [Stabzs/Angular2-Toaster#12]
I'm getting this error when I am running my tests.  I am using [angular2-seed] (https://github.com/mgechev/angular2-seed).  

When running ```npm test``` I was initially getting: ```404: /base/angular2-toaster/angular2-toaster.js```

That issue was easily fixed by adding ```'node_modules/angular2-toaster/angular2-toaster.js'``` to my ```karma.conf.js``` file.

After adding that, I began getting the error ```ReferenceError: Can't find variable: exports```

**Comment by Stabzs** [comment]
Are you loading `'node_modules/traceur/bin/traceur-runtime.js', // Required by PhantomJS2, otherwise it shouts ReferenceError: Can't find variable: require' before attempting to load angular2-toaster?  Also, are you mapping it at all in your systemjs configuration?

**Comment by mwoodsmall** [comment]
Yes I am doing both of those... my suspicion is that maybe my mapping is wrong. I'll play around with that some more.

**Comment by mwoodsmall** [comment]
here is my System.config in my test.main.js 
```
System.config({
  baseURL: '/base/',
  defaultJSExtensions: true,
  paths: {
    'angular2/*': 'node_modules/angular2/*.js',
    'rxjs/*': 'node_modules/rxjs/*.js'
  },
  map: {
    'angular2-toaster': 'node_modules/angular2-toaster'
  }
});
```

That looks right doesn't it?

**Comment by Stabzs** [comment]
Yes, the mapping looks correct.

In hindsight, I do remember having a lot of issues implementing the karma test runner.  Note that the https://github.com/Stabzs/Angular2-Toaster/blob/master/karma-test-shim.js used is a bit different from what is used in the seed.  If you follow it, something like

```typescript
Promise.all([
    System.import('angular2/src/platform/browser/browser_adapter'),
    System.import('angular2/platform/testing/browser'),
    System.import('angular2/testing')
    System.import('angular2-toaster')
]).
```
might be necessary.

**Comment by mwoodsmall** [comment]
I haven't verified loading order yet.  Your suspicion sounds reasonable though. I'll take a look into that.

**Comment by Stabzs** [comment]
If there's anything I can do to help track it down, please feel free to let me know :)

**Comment by mwoodsmall** [comment]
@Stabzs I got things working.... not super happy about what I ended up with, tho, I will post again tonight with more details

**Comment by mwoodsmall** [comment]
to get my tests running, I had to add
```  
{ pattern: 'node_modules/angular2-toaster/angular2-toaster.js', included: false },
{ pattern: 'node_modules/angular2-toaster/lib/*.js', included: false },
```
to the ```files``` section of my karma configuration file.

Then, in ```test-main.js``` I had to modify ```System.config``` to add path for angular2-toastr and map it.

```
System.config({
  baseURL: '/base/',
  defaultJSExtensions: true,
  paths: {
    'angular2/*': 'node_modules/angular2/*.js',
    'rxjs/*': 'node_modules/rxjs/*.js',
    'angular2-toaster/*': 'node_modules/angular2-toaster/lib/*.js'
  },
  map: {
    'angular2-toaster': 'node_modules/angular2-toaster'
  }
});
```

Then in the same file, I had to import it using ```System.import```
```
Promise.all([
  System.import('angular2/src/platform/browser/browser_adapter'),
  System.import('angular2/platform/testing/browser'),
  System.import('angular2/testing'),
  System.import('angular2-toaster/angular2-toaster')
])
```

**Comment by Stabzs** [comment]
Thanks for the details and perseverance on this issue. 

I'm not certain if there's a better way to structure this or if the library could make this type of testing easier. I'm open to suggestions but I'll be closing the issue for now since I don't think it's necessarily something the library is doing incorrectly.
