### ISSUE TITLE
Should setTimeout() be run outside the angular zone ?

### ISSUE THREAD

**Issue by ArnaudPel** [Stabzs/Angular2-Toaster#120]
This is more of an open discussion that an issue per se.

The gist of it is, an angular2-toaster pop-up makes protractor tests pause until the Angular zone becomes stable again. That is to say, until aforementioned pop-up disappears (timeout completes).

Not only may this slow down the whole testing process, it also makes it nearly impossible to properly test the content of a toaster message (just lost a couple of hours before figuring out the issue). For those not yet quite familiar with the concept of zones, [this article may be of interest](https://blog.thoughtram.io/angular/2016/02/01/zones-in-angular-2.html).

At the minute I've been able to improve testabilty by modifying my service that uses angular2-toaster, so that all its internal calls pass through the method below:

```
@Injectable()
export class MessageService {

  constructor(private toasterService: ToasterService,
                     private zone: NgZone) {}

  // ... methods exposed by MessageService

  private popOutsideAngular(type:string, title?: string, body?: string) {
    this.zone.runOutsideAngular(() => {
      this.toasterService.pop(type, title, body);
    });
  }
```

Now the question: would it be a good idea to run the setTimeout() that makes the popup disappear outside of angular ? Or is there some design choice behind the current behavior ?

PS: I currently depend on angular2-toaster v3, but after finding no occurrence of 'runOutsideAngular' in this github repo, I'm pretty confident my question also applies to v4

**Comment by Stabzs** [comment]
This is an interesting observation and I really appreciate you bringing it up.

I wonder if the async variant, `toasterService.popAsync()` can be expanded to run outside of the zone whereas today it only relies on `setTimeout()` to make it async.  I'd have to test this to see whether or not it still blocks.

By definition, the sync version SHOULD block, since it's synchronous.  In addition, I don't know what this will do to animation triggers if it runs outside of angular.  I'll have to test this to understand the behavior better.  I'll update this issue with my findings.

**Comment by ArnaudPel** [comment]
I'm not sure what you mean by 'block' in this context, because as far as the app is concerned, the presence of the toast doesn't block any other activity, which is sort of vital I guess. Regarding my initial question, I believe pop() and popAsync() are on the same page.

If I may try to be more explicit, what got me was that, after the toast has been shown, [the timeout set to make it disappear](https://github.com/Stabzs/Angular2-Toaster/blob/fa979fd9f10a0fc88ce8a20d6ab59c046091c561/src/toaster-container.component.ts#L217) will keep the zone in an 'unstable state'. Again, that's probably no problem for the app itself, at least I haven't been able to notice anything.

The problem arises when trying to use protractor to query the toast object, eg. `element(by.css('div#toast-container > div'))`. Because [protractor waits for Angular to become stable](https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular), the query will only be executed.. when aforementioned toast is gone.

Well to be perfectly honest, in my tests I am able to get hold of the toast element once, but the error comes when I try to query it again. While this may be ok in some cases, at the minute I see not other way than sending two protractor queries to check both title and message of the toast. And anyway, it leads to such counter-intuitive errors (at least for beginners like me), that this 'single shot' approach looks like it needs a fix.

The direction I can think of would be to run aforementioned setTimeout() outside angular, and maybe re-enter the ngZone from the callback if needs be. Lastly, it must be said that I don't claim to grasp the full implications of this idea :)

**Comment by Stabzs** [comment]
Sorry for the delay.  I wanted to thoroughly test the change to make sure that there were no adverse effects and I couldn't find any.  This has been published as version `4.0.1`.

**Comment by ArnaudPel** [comment]
More than a year later, I finally made the change, seems to work fine indeed.
Many thanks :)

**Comment by Stabzs** [comment]
@ArnaudPel heh, thanks for getting back to me :).  Glad it worked as intended.
