### ISSUE TITLE
No CSS

### ISSUE THREAD

**Issue by vbenavidesa** [Stabzs/Angular2-Toaster#121]
@Stabzs,

I create the toast and it is working (I get shown the test for the title and message) but it has no CSS style whatsoever, it just appears on my tags in the html template.
Where should I add the CSS file as I currently add it on my html file but it does nothing. Is there any other way to inject this CSS? I am using the config file to display on top right.

Thank you in advance.

**Comment by Stabzs** [comment]
Can you please be more specific as to how you are loading the library?

If you import the css manually in your HTML, you should copy the css file into your dist folder.  If you are using webpack, all you have to do is import the css (see https://github.com/Stabzs/Angular2-Toaster#import-css).

If you can please add some specifics around what you're doing, I can point you in the right direction.

**Comment by vbenavidesa** [comment]
I kind of solved this issue using a cdn to import the css. But another issue emerged... I cannot use the toaster unless there is an specific html tag to target, I wonder if you can inject it somewhere without being targeted to an specific tag.
My problem is that I have an error handler class that handles all errors that can appear when consuming web services like "bad request" or "internal server error" or "not found", but that is handled outside of the current html space. I try to fire the error handler to make a toast but then I got the "no container" error because its not sitting on the current html page.

**Comment by Stabzs** [comment]
@vbenavidesa glad to hear you got the CSS import issue solved.

I'm not exactly sure what you want the library to do in that case.  Are you asking if it can attach to the html element or body element instead?  If you need to do that, you should simply put the `<toaster-container></toaster-container>` element at the most root element you possibly can in your application, and definitely outside of your router.

**Comment by vbenavidesa** [comment]
Thank you @Stabzs, I completely left that out of my head, I put my container in the root app.component.ts outside of the router and it worked wonderfully, sorry for disturbing your saturday night with such stupid question. Completely blacked out for that!

**Comment by Stabzs** [comment]
@vbenavidesa no need to apologize!  Glad that met your needs!
