### ISSUE TITLE
Translation features

### ISSUE THREAD

**Issue by rubyduby** [Stabzs/Angular2-Toaster#123]
How do you guys go about translating toasts?

One would have to use some kind of template to pass into the toasterservice. Any plans on adding translation features?

**Comment by Stabzs** [comment]
I'll leave this open for a bit for discussion from the community, but no this was never intended to be a feature in angular2-toaster since it would bloat the library and could be achieved via components. 

How exactly would you expect the library to handle translation?

**Comment by Newan** [comment]
Example:
        this.translate.get(['key.save', 'key.save_form']).subscribe( (res) => {
          this.toasterService.pop('success', res['key.save'], res['key.save_form']);
        });

**Comment by pdotkriz** [comment]
Hey Newan, 
I tried in the below 
translate.setTranslation('en', {
      INVALID_CREDENTIALS: 'Invalid Credentials'
  });
 this.translate.get('INVALID_CREDENTIALS').subscribe((res: string) => {
      this.toasterService.pop(this.createToast("success", "Success",res));
    });
but unfortunatley pop up shows INVALID_CREDENTIALS not Invalid Credentials 
do you have any suggestion ?
