### ISSUE TITLE
If page redirect to one component to another component show toaster.

### ISSUE THREAD

**Issue by 02harleen** [Stabzs/Angular2-Toaster#127]
Hi, How possible if redirect one component to another component show toaster. How it is possible please tell us?

**Comment by Stabzs** [comment]
Redirection has nothing to do with showing a toast.  They are two separate problems. You can show it on componen instantiation or as part of a route complete hook. 

If you can provide more details on what you're trying to do, I am happy to attempt to point you in the right direction but this isn't a lack of functionality in the library.

**Comment by 02harleen** [comment]
Hi, I explain in detail:- 

Toaster creates a service and if go to one component to another component show toaster other vise does not show.

**Comment by Stabzs** [comment]
This really isn't related to the library and I'm closing the issue. If you'd like to create a plunker I'm happy to try to guide you but this is too broad and unrelated to leave open.
