### ISSUE TITLE
Global container

### ISSUE THREAD

**Issue by chriscamicas** [Stabzs/Angular2-Toaster#13]
Any chance we could have a global toaster-container (say in the root component), and fire toasts from child components using only the service injection ?
Thanks

**Comment by chriscamicas** [comment]
My bad... I had the service in both parent and child providers and thus broke the dependancy injection singleton.
Solution: root component
```javascript
import {ToasterContainerComponent, ToasterService} from angular2-toaster

@component({
...
template: '<toaster-container></toaster-container>',
providers: [ToasterService],
...
})
```

child component
```javascript
import {ToasterService} from angular2-toaster

@component({
...
template: '',
providers: [],
...
})
export class ChildComponent {
    constructor(private _toasterService: ToasterService) {
        //ToasterService is resolved by the Injector hierarchical tree from the root provider
    }
```

**Comment by Stabzs** [comment]
Can I consider this a non-issue since it seems like you found the solution you were looking for?

**Comment by chriscamicas** [comment]
Sure, I closed it
Sorry for the disturbance
