### ISSUE TITLE
Check mark

### ISSUE THREAD

**Issue by SGDanie1** [Stabzs/Angular2-Toaster#130]
![screenshot from 2017-09-21 17-45-31](https://user-images.githubusercontent.com/31034579/30702715-55cc2c88-9ef6-11e7-8005-9b6a80c5200b.png)

Should the check mark of "success toaster" look like this or something is gone wrong?

**Comment by Stabzs** [comment]
Something has gone wrong. Can you please create a plunker that demonstrates the issue?
