### ISSUE TITLE
Problems resolving RxJS classes in ToasterService after prod build

### ISSUE THREAD

**Issue by brian428** [Stabzs/Angular2-Toaster#131]
For folks that manually bundle only a subset of RxJS (only what is used by an app), I would mention in the readme that `rxjs/add/operator/share` needs to be included. I wasn't including it, and it took some debugging to figure out that I needed to add it.

**Comment by brian428** [comment]
Never mind (for now at least). I've got some other problem going on (`Observable is not a constructor` error). Which is bizarre, because I use Observable all over my own app code. Anyway, sorry for the false alarm.

**Comment by Stabzs** [comment]
Thanks for the update and please feel free to reopen this thread if additional documentation is needed.

**Comment by brian428** [comment]
Stabzs, I wanted to follow up on this to see if you have any ideas. If you'd rather not deal with "support requests" here, just let me know and I'll understand. But since you're doing the bundling I thought maybe you'd have an idea here.

I'm using Minko's angular-seed project, which uses SystemJS. I can add the angular2-toaster UMD bundle to my SystemJS config. In dev mode, everything is fine. But when I do a prod build (AoT +  bundling), I get the `Observable is not a constructor` error in ToasterService.

If I debug the prod build, at the point of the error, the local variables containing the import results for RxJS `Observable` and `Subject` are null. So clearly, the problem is that within the `ToasterService`, the import lookups for the RxJS dependencies aren't being resolved.

This is completely baffling, because obviously I do have RxJS included. Angular and PrimeNG depend on RxJS and they work fine. And I use RxJS extensively throughout my own code. In fact, _I can take the raw TS source for Angular 2 Toaster and include it (with no changes) alongside my own app source_, and everything builds and runs fine after a prod build.

It's like the "import scope" within the UMD bundle is isolated in some way, and isn't resolving the imports in the same way that the rest of the code does. 

I'll admit that I have an embarrassingly limited grasp of the differences between JS module types, and a limited grasp of the arcane workings of SystemJS. So it's possible that I'm just an idiot and am doing something wrong. But I have no idea what my mistake might be. Again, I'm using RxJS all over the place, and am using other libs that depend on RxJS. Toaster is the only piece that's having problems.

Do you have any idea what might be going on? Can you think of anything "special" about the way you're building the UMD bundle that could cause this?

Thanks in advance.

**Comment by Stabzs** [comment]
@brian428 This is really curious...

It would seem that something in either the AoT or the bundling step is removing the imported references via some form of what it thinks is dead code elimination.

However, without a bit more information, it is really difficult to help provide additional direction or determine if there is currently a bug in rxjs imports within angular2-toaster, which could be possible.

Minko's seed doesn't seem to use SystemJS and I haven't had issues with the demo plunker or the demo apps, but granted, they aren't running AoT.  Would you be able to create as small of a reproduction app as possible?  I'd love to dig further into this but without seeing how you are currently building your project, I'm afraid I'd simply be taking guesses.

**Comment by brian428** [comment]
Here's a bare-bones example of the angular-seed project with angular2-toaster.

To start with, do an `npm install` and then `npm start`. You'll see everything works fine.
Stop the app, then start it again with ``npm run serve.prod.aot` to see the `Observable is not a constructor` error`.

I don't think the imported references are being "removed", it seems more like the lookup of the RxJS types is returning null, so when `ToasterService` tries to use those objects, it blows up.

As I said, the bizarre piece of this is that I can take the angular2-toaster source, paste it into my own app, adjust my imports to the proper paths (rather than using node_modules), and it all works fine even after an AoT build. So I'm rather stumped.

Let me know what you think if you have a chance to try it out. For now I'll re-open this ticket and you can close it if you figure out the problem (or get tired of doing detective work heh).

Thanks.
[angular-seed-toaster.zip](https://github.com/Stabzs/Angular2-Toaster/files/1331700/angular-seed-toaster.zip)

**Comment by brian428** [comment]
Oh, to save you a bit of time (maybe?), SystemJS is configured to include angular2-toaster in `angular-seed-toaster/tools/config/project.config.ts`, line 55.

**Comment by Stabzs** [comment]
@brian428 I spent quite a bit of time on this last night and this is pretty odd.

The require statements for the umd angular2-toaster file are exactly the same format as any of the imported angular files and you can see that reflected in the prod build:

angular2-toaster:
`"object" == typeof exports && void 0 !== module ? factory(exports, require("@angular/core"), require("@angular/platform-browser"), require("@angular/animations"), require("rxjs/Observable"), require("rxjs/add/operator/share"),`

part of the angular dependencies:
`"object" == typeof exports && void 0 !== module ? factory(exports, require("@angular/common"), require("@angular/core"), require("rxjs/BehaviorSubject"), require("rxjs/Subject"), require("rxjs/observable/from"`

As a result, it SEEMS that the bundle is doing its job correctly so I am tempted to rule that out.  This may be more of a shimming issue, although I'm not sure why this only shows up in the AoT build or what is being removed.  I'll continue to look into this but I'm as confused as you are and any community help would be greatly appreciated.

**Comment by brian428** [comment]
I pinged Minko via his project just to see if a quick look over the symptoms here reveals any answers. He's a really busy guy, so I'm not sure if or when he'll be able to take a peek, but I'm hoping he might have some idea of what could be going on.

**Comment by Stabzs** [comment]
@brian428 thanks :).

I'm starting to think that whatever Observable is getting injected into `angular2-toaster` has been shimmed earlier, but I can't find where that is happening.  It doesn't seem to be the same object as in other instances however so perhaps it is an import order problem.

**Comment by Stabzs** [comment]
@brian428 I've spent quite a bit more time on this.  

I've rebuilt the rollup-config to match all of the `@angular` packages which bloats out the unminified umd from 25kbs to about 120kbs with no luck.  I've downgraded typescript to 2.3.x and SystemJS to 0.19.x and that was also fruitless.

I even rebuilt the Observable constructor functions to use the .create helpers instead, hoping maybe the constructor was missing but the prototype still existed, even though I figured that wouldn't matter...and it didn't.

What's really interesting is that the prod build itself runs absolutely fine.  So this is definitely an optimization step within the AoT build itself that is not caused by minification or rebundling, but rather some step to support AoT.  I'm running into dead ends.

There may very well be something that is missing from `angular2-toaster` that is causing issues with AoT, but I honestly have no idea at this point what it might be.  There may also be a loading order that differentiates the `@angular` packages from how `angular2-toaster` behaves, but I'm also not sure what that would be either.  I may continue trying to dig some on this but I need some help from someone who understands the AoT + SystemJS compilation nuances better than I do.

**Comment by Stabzs** [comment]
@brian428 I still don't have an answer on this, but I'd like to know if it is still a problem when targeting Angular 5, especially in conjunction with the latest angular2-toaster@5.0.0-beta.1 build.  I'd appreciate your feedback when you have time.

Thanks!
