### ISSUE TITLE
Occasionally Slow toasts

### ISSUE THREAD

**Issue by AshMcConnell** [Stabzs/Angular2-Toaster#133]
I'm not sure how to describe it, but we occasionally get toasts that are delayed.  I output a console.log and it could be 10-20 seconds before the toast appears.

Can anyone think of any reason that this would be the case.  

**Note**  I am on Angular 4.4.4 and it seemed to work fine on Angular 2

**Comment by Stabzs** [comment]
This is most likely an implementation issue in your code.  Can you provide a reproduction of the issue in a plunker?
