### ISSUE TITLE
Global container using LocationStrategy and module routing 

### ISSUE THREAD

**Issue by pedropapa** [Stabzs/Angular2-Toaster#135]
Hello.

I wonder how can I use a single container in the app root and let every `toasterService` call refer to that container.

The reason I want it is to avoid the toast message from disappearing while showing it and changing route at the same time. For example: In the /login route, the user logs in and the message "Login succeed" is shown, then I need to redirect the user to the logged route right away. Currently, the message is not shown because of the route change.

I've already looked into issues #129, #98, #40 and #13 with no luck.

**Comment by Stabzs** [comment]
@pedropapa sorry for the delay on responding to this issue.  Can you provide a plunker that demonstrates how you are currently architecting your application?  Using a single container in the app root is the currently recommended strategy for exactly the type of behavior you are trying to accomplish, but without seeing how you have structured your project, it is very difficult to provide any insight.
