### ISSUE TITLE
Toaster not dissapearing - Angular 5

### ISSUE THREAD

**Issue by engineers-nemanjag** [Stabzs/Angular2-Toaster#137]
This is how my toaster is configured:

```
const toast: Toast = {
      type: 'error',
      title: 'Oh Snap !',
      body: errMsg,
      showCloseButton: true,
      timeout: 5000
    };
```

The problem is that it doesn't disappear, it only disappear if i move mouse over it after the 5s (the timeout). Any advice?

**Comment by sambanthar** [comment]
i am facing the same problem but i move over to the toaster its dissapearing

**Comment by sulhome** [comment]
I think as a workaround if you just import `BrowserAnimationsModule` then it should work for now
I had an issue where the text was not showing on the toast until I hover over it
after adding `BrowserAnimationsModule` to my import the issue seems to disappear.
```typescript
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
```

**Comment by engineers-nemanjag** [comment]
I found the solution, just deleted the timeout from my configuration... Dumb but hey, it dissapears

**Comment by luishmcmoreno** [comment]
I found the solution just updating the angular2-toaster module from 4.0.0 to 5.0.1.
