### ISSUE TITLE
Close button is not responsive

### ISSUE THREAD

**Issue by GabCeb95** [Stabzs/Angular2-Toaster#139]
Hi,

We found an issue with the responsive design(you can check it on your demo app on plunkr), the "X" goes to the right bottom of the box when the window is smaller...

Thanks!

![image](https://user-images.githubusercontent.com/18234563/34541408-b1a9957e-f09d-11e7-8913-af53f51cbb78.png)

**Comment by Stabzs** [comment]
This is currently fixed in 5.0.0-beta.1 and will be released in the full 5.0.0 release.

**Comment by Stabzs** [comment]
Released in 5.0.0.
