### ISSUE TITLE
Angular 2 beta 17 console warning

### ISSUE THREAD

**Issue by jonnyklemmer** [Stabzs/Angular2-Toaster#14]
Hey,

Just wanted to shoot over an issue caused by a "breaking" change in beta 17 
> Inside of structural directives that declare local variables, such as *ngFor, usage of #... is deprecated. Use let instead.
> (ref https://github.com/angular/angular/blob/master/CHANGELOG.md)

The following is the new warning caused by the Angular2-Toaster container component template.

> Template parse warnings:
> "#" inside of expressions is deprecated. Use "let" instead! ("="[toasterconfig.positionClass, toasterconfig.animationClass]" class="ng-animate">
>             <div [ERROR ->]*ngFor="#toast of toasts" class="toast" [ngClass]="toasterconfig.typeClasses[toast.type]" (click)="cl"): ToasterContainerComponent@2:17

Should be a simple fix & I'd be happy to help with a PR! Thanks!

**Comment by Stabzs** [comment]
Thanks for the head's up!

I'm currently updating the library to `@angular: 2.0.0-rc.1`.  This and other important upgrade features/functionality will be added with the next release.  I'll leave this open for tracking in the menatime.
