### ISSUE TITLE
Angular CLI build fails because typeClasses and iconClasses have no index signature

### ISSUE THREAD

**Issue by andrewpmontgomery** [Stabzs/Angular2-Toaster#148]
Bug report
---

When I create a new project using angular-cli (v1.7.2) and Angular2-Toaster (v5.0.0), `ng build` returns the following error:

```
ERROR in
node_modules\angular2-toaster\src\toaster-container.component.d.ts.ToasterContainerComponent.html(8,17): 
  Element implicitly has an 'any' type because type 'Object' has no index signature.
node_modules\angular2-toaster\src\toaster-container.component.d.ts.ToasterContainerComponent.html(5,17): 
  Element implicitly has an 'any' type because type 'Object' has no index signature.
```

This is because `toaster-config.ts` has the following definitions:
- `typeClasses?: Object;`
- `iconClasses?: Object;`

and `toaster-container.component.ts` has the following HTML template:
- `[ngClass]="toasterconfig.typeClasses[toast.type]"`
- `[iconClass]="toasterconfig.iconClasses[toast.type]"`

I'll provide a PR to fix this.

**Comment by Stabzs** [comment]
@andrewpmontgomery I've actually failed to reproduce this now in several attempts.  Can you please describe the base configuration required to reproduce this?  i want to make sure the project is properly configured to highlight these issues going forward.

**Comment by andrewpmontgomery** [comment]
You can reproduce the problem in your latest branch simply by changing:
`"suppressImplicitAnyIndexErrors": false,`
to
`"suppressImplicitAnyIndexErrors": true,`
in the `tsconfig-aot.json` file.

I can't reproduce this in a sample consuming application, so perhaps something has changed in angular-cli or another package.
