### ISSUE TITLE
Inline Style

### ISSUE THREAD

**Issue by darklinki** [Stabzs/Angular2-Toaster#153]
This may be a totally dumb question but I don't get it. 

I try to use inside of the body inline styling like:

` <div style="width: 200px;">`

The tags it self works but the style gets removed and I receive the following message:
WARNING: sanitizing HTML stripped some content (see http://g.co/ng/security#xss).

I already set bodyOutputType: BodyOutputType.TrustedHtml,

Edit: Class definition doesn´t get removed but I can't access the class from outside.

**Comment by darklinki** [comment]
First: With this.sanitizer.bypassSecurityTrustHtml on the body input I got it working.
My only problem is now the fixed with of 300px. How do I change the size of the toaster without touching the default css ?

**Comment by Stabzs** [comment]
@darklinki correct, Angular will prevent the content unless you explicitly mark the element as bypassing normal security levels.

As long as you load the toaster.css before your custom css, you can override the width to your liking:

```css
#toast-container > div {
  width: 400px;
}
```

**Comment by darklinki** [comment]
@Stabzs  @Stabzs Ty yes, I will get it to work some how. 
Would be cool if it will be a feature anytime. Like the position.

**Comment by Stabzs** [comment]
@darklinki I'll have to give that some thought.  Ideally I'd prefer that this is managed via SCSS variable compilation or drop-in CSS overrides since this probably isn't a common first-class use case and could potentially affect the responsive design.  It is something I can take a closer look at.
