### ISSUE TITLE
css is not working

### ISSUE THREAD

**Issue by RoraxHan** [Stabzs/Angular2-Toaster#159]
@import 'node_modules/angular2-toaster/toaster';

I added above code to my component's scss file to work toaster correctly.
component is in the app/pages/my-component
but toaster is appearing at the bottom. css is not imported. what's wrong?

**Comment by Stabzs** [comment]
Impossible to tell from your description. 

Can you please create an example that demonstrates the problem please?

**Comment by RoraxHan** [comment]
![screen shot 2018-04-29 at 1 07 30 am](https://user-images.githubusercontent.com/25556402/39399059-c852b916-4b49-11e8-8b9b-17cc6aefd831.png)

toast is displaying like this.
my component is in the app/pages/upload-csv.

So I added the following code to app/pages/upload-csv.scss

`@import 'node_modules/angular2-toaster/toaster';`
but the problem is not solved.

**Comment by Stabzs** [comment]
I’m sorry I missed your update. 

What happens if you include the scss higher in the component tree?
