### ISSUE TITLE
Way too awesome!

### ISSUE THREAD

**Issue by haswillb** [Stabzs/Angular2-Toaster#16]
Hey there, I didn't know how else to contact you but I wanted to say thank you! I just upped my app to the Angular 2 rc and totally thought I'd have to rip out the toaster for now. I was really impressed to see that you've already made the move.

Thanks for being an absolute gem, you've made my life very nice!

**Comment by Stabzs** [comment]
No problem!  

Thanks for the awesome feedback!  It's great to hear that the library is being used and abused, especially in new apps staying on the Angular 2 edge.  It's been a bit tricky keeping up with the breaking changes, but I'm happy to do so and keep it as closely behind as possible.

Thanks again for the wonderful feedback and glad it's been so helpful to you and your projects!
