### ISSUE TITLE
Please add support for Angular 6.0

### ISSUE THREAD

**Issue by KhodeN** [Stabzs/Angular2-Toaster#161]
Angular 6.0 uses RxJS 6.x

Now `angular2-toaster 5.0.1` fails on compile:
```./node_modules/angular2-toaster/src/toaster.service.js
Module not found: Error: Can't resolve 'rxjs/Observable' in '/private/tmp/st-cloud-six/node_modules/angular2-toaster/src'
```

I can use `rxjs-compat` module, but it is workaround

**Comment by Stabzs** [comment]
I'll be looking to get an Angular 6 release pushed soon.  Sorry for the delay.

**Comment by anth0** [comment]
Any news on the planned release?

**Comment by razfriman** [comment]
This is being worked on in: https://github.com/Stabzs/Angular2-Toaster/pull/162
