### ISSUE TITLE
Angular ErrorHandler

### ISSUE THREAD

**Issue by dgsqrs** [Stabzs/Angular2-Toaster#169]
Hi there
This is not a bug but a feature/example request.

I have a custom ErrorHandler. My custom implementation is very simple, it implements the interface ErrorHandler and overwrite the handleError(error) method.
Because the ErrorHandler does not operate in a Angular Zone, the toasts don't show up correctly. I found the way to do it here : https://stackoverflow.com/questions/44975477/angular2-ng-toasty-errorhandler

The request : Can you add an example of the "correct" way to implement this kind of handler ?
Thanks !

**Comment by Stabzs** [comment]
Thank you for opening this. This is a common “complaint” and having a definitive solution is an excellent thing. 

I’ll add an example to both the angular-cli app and the documentation.

**Comment by Stabzs** [comment]
This has been added as part of the 6.1.0 release.
