### ISSUE TITLE
Is there a version targeting Angular 2 beta.15?

### ISSUE THREAD

**Issue by BrainCrumbz** [Stabzs/Angular2-Toaster#17]
... as per issue title ... Thank you

**Comment by BrainCrumbz** [comment]
Nevermind ... it seems like *0.2.0-beta.0* is the answer, at least after package install and running build.

**Comment by Stabzs** [comment]
You are correct, *0.2.0-beta.0* is the appropriate version for Angular2-beta.*. If targeting beta.17, a warning will be thrown but functionality should be intact. 

Keep in mind that Angular2-beta.* will be considered unsupported and bug fixes going forward will only be for RC and beyond. That said, the functionality should be complete enough for your needs while targeting beta versions.

**Comment by BrainCrumbz** [comment]
Yep. We plan to move on to Angular2 RC or RTM as soon as things settle a little bit, especially on the router side. Now we have a custom router outlet for authenticated/public paths, and it seems there still are moving parts on that side. Thanks for your reply!

**Comment by Stabzs** [comment]
Completely understandable.  Considering the current state of flux, I can't blame you at all.  Good luck in your future migrations and my pleasure.
