### ISSUE TITLE
Request for Angular Universal Support

### ISSUE THREAD

**Issue by starkpratik** [Stabzs/Angular2-Toaster#174]
Hello, it seems a great library to have but just to know if this is supporting angular universal?
This will be a great feature to have.

**Comment by Stabzs** [comment]
With the exception of animations (which seems to be an issue with angular core) the library works just fine.  Is there a particular behavior that you have observed that is incompatible?

**Comment by starkpratik** [comment]
I'm using angular 4 can you let me know which version is supported as it is giving me version compatibility error. Angular 4.2.4

**Comment by Stabzs** [comment]
While I would not recommend using anything less than Angular 6 and the latest `angular2-toaster` builds/releases, you can target the last 4.x.x pinned release: https://unpkg.com/angular2-toaster@4.0.2/
