### ISSUE TITLE
Why does toaster service inside Global Error Handler wont work in Angular4/5/6?

### ISSUE THREAD

**Issue by chakri1986** [Stabzs/Angular2-Toaster#175]
My requirement is to load some data by calling Two Rest Api's before app component loads [First step].If API gives any error display the message in Toaster (angular2-toaster) from Global Error Handler

![image](https://user-images.githubusercontent.com/36687981/43042285-69cdaf64-8d97-11e8-9465-63c51f291ae7.png)

![image](https://user-images.githubusercontent.com/36687981/43042291-8f8acc1e-8d97-11e8-9e92-72fe8a7bb661.png)

![image](https://user-images.githubusercontent.com/36687981/43042306-befa07b2-8d97-11e8-8c8e-7bf2d909f945.png)

![image](https://user-images.githubusercontent.com/36687981/43042308-ccecb4b4-8d97-11e8-8fe6-bd7140e9118b.png)

![image](https://user-images.githubusercontent.com/36687981/43042313-da1ddd98-8d97-11e8-872c-1ab7b77cb15f.png)

Reference: https://stackoverflow.com/questions/51444006/why-does-toaster-service-inside-global-error-handler-wont-work-in-angular4-5-6

**Comment by Stabzs** [comment]
This is an interesting problem and not typically a recommended approach. Is it possible for you to create a repo that demonstrates the problem? It would be very helpful.

**Comment by chakri1986** [comment]
I will try to create a Repo, but what would be the recommended approach ? Can you pls suggest me.

**Comment by Stabzs** [comment]
If you could create a sample barebones app (and even host it on GitHub) that demonstrates the behavior that would make it much easier to reproduce. While I appreciate the screenshots, it will be difficult for me to exactly reproduce your scenario and actual code would be very helpful.

**Comment by Stabzs** [comment]
If you can provide a reproduction I’ll be happy to reopen the issue.
