### ISSUE TITLE
BodyOutputType Component

### ISSUE THREAD

**Issue by crissty** [Stabzs/Angular2-Toaster#176]
Hi,
Fisrt, congratulations for this component, it is powerful and simple.
It is possible to see a example of Toastr with BodyOutputType.Component? This is a little confuse for me.

Thanks!!

**Comment by rmeshksar** [comment]
I created an example of using Angular component as body in toaster here. Hope it helps:

https://stackblitz.com/edit/angular-1ghfmd

**Comment by Stabzs** [comment]
@rmeshksar  thanks for making an example!
