### ISSUE TITLE
Unable to configure TapToDismiss on a Toast by Toast basis

### ISSUE THREAD

**Issue by benhaynie** [Stabzs/Angular2-Toaster#178]
In my application, I want to be able to tapToDismiss some Toast messages, and not enable this property on other messages.  For example, one Toast message may include a link for the user to click on.  On these messages, I want to disable the tapToDismiss.  On other Toast messages, I want to be able to tapToDismiss.

Prior to version 5, there was a ToastConfiguration property on the Toast object.  This allowed us to set the tapToDismiss property on an individual Toast method.  

This property has been removed.  

Is there a recommended pattern to achieve this behavior?  I understand that there is a Config object that can be used, but this seems to be a global setting, and not on a Toast by Toast basis.

**Comment by Stabzs** [comment]
I apologize for inadvertently removing functionality, even if it wasn't exactly intended for that use case.

Let me look into expanding the toast api to allow for tapToDismiss functionality per toast.

**Comment by Stabzs** [comment]
This has been closed in version 11.0.0
