### ISSUE TITLE
Toast not showing until click on layout when using with ng-bootstrap Modal 

### ISSUE THREAD

**Issue by praveen-238** [Stabzs/Angular2-Toaster#179]
I am using a modal from ng-bootstrap. When I create a toast while the modal is still open but in the process of being closed using this.toastrService.popAsync('Error') this toast does not show up until I click somewhere on the page.

**Comment by Stabzs** [comment]
Are you able to create a minimal example that demonstrates the problem by chance?  Thanks!

**Comment by szantogab** [comment]
@praveen-238 @Stabzs any update on this? any workarounds?
