### ISSUE TITLE
karma unit tests fail with 'No Toaster Containers have been initialized to receive toasts'

### ISSUE THREAD

**Issue by Iam-surendra** [Stabzs/Angular2-Toaster#183]
i defined container in app component which is the root component of my application, its working fine.

when it comes to the unit tests component level spec file doesn’t get the toaster container instance that we are specified in the app component. 

We are getting following error for all the components that are used toasters.

**No Toaster Containers have been initialized to receive toasts.**

its not possible to add container reference each component or spec file.

can you please help me how can i resolve this ?

**Comment by Stabzs** [comment]
There are a number of test examples in the repository.  It might be helpful for you to review those tests and see if it helps

If you can create a minimal reproduction I'd be happy to look at it.
