### ISSUE TITLE
Maintain notification position whilst scrolling

### ISSUE THREAD

**Issue by NathenSample** [Stabzs/Angular2-Toaster#184]
Hi there,

I'm running into an issue which is much more likely to be PEBKAC than it is to be an actual problem with the library, but hoping to get some advice nonetheless.

When using angular-toastr  I'm able to set the position of the toast to appear in the top right, when I scroll down a page this position is maintained and the notification remains, in the top right.

However, when using angular2-toastr when I set the position to top right and scroll down the page the notification remains where it first appeared, thus scrolling off the page.

This means on large pages when I receive a notification I don't actually see it, as its in the top right of the page, which is currently not in the viewport.

No custom CSS effects the position of the toast, and no position directive is passed to the object, instead being left to default to top-right.

Any assistance would be appreciated.

**Comment by Stabzs** [comment]
To clarify a few things...

This is `angular2-toaster`, not `angular2-toastr`.  If you are using `angular2-toastr` you have the wrong repo.

The `#toast-container` is position fixed meaning it will remain in the same position regardless of how you scroll.  As a result, the toast shouldn't be moving as you scroll but rather it should scroll with you.  You can see a demo of this functionality in a simplistic fork of the demo plunkr.  http://next.plnkr.co/edit/pvdQkui6ns4lZvYS

**Comment by NathenSample** [comment]
Issue ended up being me being blind, and not spotting that there was indeed a custom CSS rule applying.

Thanks for the assist regardless.

PEBKAC.
