### ISSUE TITLE
Body is not updated when bodyOutputType is TrustedHtml

### ISSUE THREAD

**Issue by rmeshksar** [Stabzs/Angular2-Toaster#186]
When the toast object is created, updating the title and body values of the object should update the toast component.
It works well in default mode and title is working in all cases.
However, when the bodyOutType is TrustedHtml, the body in the component is not getting updated.
It is due to the fact that the trusted html for the body is only calculated in the component initialization phase and not reacting to the changes.
The solution to this is to use sanitizeHtml pipe and apply it to the toast.body in the component template.

I create this PR to fix this issue:
https://github.com/Stabzs/Angular2-Toaster/pull/185

That would be great if it can be reviewed and merged if it is all fine.

**Comment by Stabzs** [comment]
I missed the PR.  Thank you for opening this issue to bring this to my attention and thank you for the contribution.  I will look into it.

**Comment by rmeshksar** [comment]
Any update on this,

**Comment by Stabzs** [comment]
This has been fixed in version 11.0.0.
