### ISSUE TITLE
Error : callback.apply is not a function

### ISSUE THREAD

**Issue by cyberbobjr** [Stabzs/Angular2-Toaster#19]
Hi,
i've an error when i use Angular2-toaster with angular2 rc.0. The toaster appears and i have this exception in the console :
EXCEPTION: Error: Uncaught (in promise): TypeError: callback.apply is not a function
[...]

Thanks for your help,
best regards

**Comment by Stabzs** [comment]
Can you please provide a small complete plunkr that demonstrates this behavior?  Thanks.
