### ISSUE TITLE
retarded documentation

### ISSUE THREAD

**Issue by Porkechebure** [Stabzs/Angular2-Toaster#195]
Documentation shows everything.... and not toast types....
error, success and????

LOL this should be the first thing shown after configuration.....

**Comment by fidian** [comment]
As a hint to others, the types are defined in [toaster-config.ts](https://github.com/Stabzs/Angular2-Toaster/blob/master/src/toaster-config.ts#L60).

**Comment by Stabzs** [comment]
This has been updated in 10.0.0.  While I appreciate you bringing it to my attention, for future reference, a kinder approach would be wonderful :).
