### ISSUE TITLE
Extend peer dependencies to Angular 9

### ISSUE THREAD

**Issue by jeffpardy** [Stabzs/Angular2-Toaster#198]
**Issue description**

running npm install throws the following warning:

```
npm WARN angular2-toaster@8.0.0 requires a peer of @angular/common@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-toaster@8.0.0 requires a peer of @angular/compiler@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-toaster@8.0.0 requires a peer of @angular/core@^8.0.0 but none is installed. You must install peer dependencies yourself.
```

**Steps to reproduce and a minimal demo of the problem**

`npm install` with Angular 9

**Current behavior**

`npm install` shows a couple of warning due to peer dependencies.

**Expected/desired behavior**

No warnings should be shown

**Comment by Stabzs** [comment]
This has been republished under version 10.0.0.  At this time I am not planning on retrofitting a 9.0.0 release.
