### ISSUE TITLE
SystemJS shouldn't be supported

### ISSUE THREAD

**Issue by mbalex99** [Stabzs/Angular2-Toaster#2]
Since I'm using Webpack at the moment, SystemJS seems redundant. 
I think that's a project specific choice to be made. Since this is a 3rd party module, shouldn't it just conform to the typescript es6 export format?

**Comment by Stabzs** [comment]
I'll remove the SystemJS requirement and I'll update the typescript build to use CommonJS.  This is consumable by Webpack and will be far cleaner.

**Comment by Stabzs** [comment]
angular2-toaster.ts was removed from the build.  angular2-toaster.js now uses es6 module export syntax.
