### ISSUE TITLE
Cannot read property 'unsubscribe' of undefined!!!

### ISSUE THREAD

**Issue by dsl-src** [Stabzs/Angular2-Toaster#20]
I use authorization component which checks if user is authorize to see protected page where I have and SimpleNotificationsComponent. In case of unauthorized attempt, the authorization component uses Router and navigates to login page. And in that case I got:

Unhandled promise rejection TypeError: Cannot read property 'unsubscribe' of undefined(…)

which leads to NotificationComponent and:

ngOnDestroy()
 {
this.addToastSubscriber.unsubscribe()
 this.clearToastsSubscriber.unsubscribe()
 }

It is probably because of component not being initializes in ngOnInit.

**Comment by Stabzs** [comment]
The listener that is trying to unregister doesn't appear to be part of the toaster component. Can you please create a small plunkr that demonstrates this behavior?

**Comment by dsl-src** [comment]
I made the Pull Request to fix this problem. 
Please accept it. I really like this library but this problem does not allow her to use.

**Comment by Stabzs** [comment]
This has been published as `0.3.1-rc.1` via https://github.com/Stabzs/Angular2-Toaster/commit/b88eb5a0db0382cb9bf032d19c5b10f8d1eba7d8.

Please note that while coveralls reported test coverage remained at 100%, branch coverage dropped and had to be corrected in the above commit.  Going forward, if you contribute, please make sure to add appropriate tests and regenerate test coverage to ensure proper coverage of all code paths and branches.
