### ISSUE TITLE
Error with Angular 9

### ISSUE THREAD

**Issue by maxailloud** [Stabzs/Angular2-Toaster#202]
Hello,
I am using this package since a while and after updating to Angular 9 I have an issue I think related to it.

I have an `AppNotificationModule` used in my main component importing `ToasterModule.forRoot()`.
In the module I have the component with the template pretty much being `<toaster-container [toasterconfig]="toasterConfig"></toaster-container>`.
I also have a AppNotificationService that I use to ease the use of the `ToasterService` provided by the package.

When I build with Angular 9 (with Ivy) I get no errors but when serving I get that:

```Uncaught Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
    at getCompilerFacade (core.js:636)
    at Function.get (core.js:38869)
    at registerNgModuleType (core.js:35936)
    at core.js:35954
    at Array.forEach (<anonymous>)
    at registerNgModuleType (core.js:35950)
    at core.js:35954
    at Array.forEach (<anonymous>)
    at registerNgModuleType (core.js:35950)
    at new NgModuleFactory$1 (core.js:36112)
```
Do you know if it's something I missed in using the package or is it a bug with Angular 9 (or Ivy maybe)?

My version in case you need it:
```Angular CLI: 9.0.6
Node: 13.2.0
OS: darwin x64

Angular: 9.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.6
@angular-devkit/build-angular     0.900.6
@angular-devkit/build-optimizer   0.900.6
@angular-devkit/build-webpack     0.900.6
@angular-devkit/core              9.0.6
@angular-devkit/schematics        9.0.6
@angular/cdk                      9.1.3
@ngtools/webpack                  9.0.6
@schematics/angular               8.0.6
@schematics/update                0.900.6
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
```

**Comment by Tazaf** [comment]
Hi @maxailloud 

I had the exact same issue in my app after upgrading to Angular@9.

In my case, it was caused by the (incorrect) way the `ToasterModule` was imported in my `SharedModule`:
```ts
// The INCORRECT import, note the path
import { ToasterModule } from 'angular2-toaster/angular2-toaster';
```
Changing the import to the one below resolved the issue. The app still compiled successfully but serving it did not raise that infamous `Angular JIT compilation failed` error.

```ts
// The fixed import
import { ToasterModule } from 'angular2-toaster';
```
Maybe this applies to your issue as well? I sure hope it does ; I've lost hours running after this problem and would be glad to know this helped you resolve yours 😄

**Comment by maxailloud** [comment]
Thank you @Tazaf it worked.

**Comment by Stabzs** [comment]
@Tazaf thanks the assistance :).

I can add this to the FAQ, or feel free to submit a PR to add it if you would like to.  I believe the documentation only references `import { ToasterModule } from 'angular2-toaster';`, but I will review the documentation again to make certain.
