### ISSUE TITLE
Extend peer dependencies to Angular 10

### ISSUE THREAD

**Issue by susan12468** [Stabzs/Angular2-Toaster#210]
**I am using Angular 10 with angular2-toaster 8 and getting the following warnings. What am I supposed to do to make it work with Angular 10? Thanks.**  

npm WARN angular2-toaster@8.0.0 requires a peer of @angular/common@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-toaster@8.0.0 requires a peer of @angular/compiler@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-toaster@8.0.0 requires a peer of @angular/core@^8.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by Stabzs** [comment]
This is now published as version 10.0.0.
