### ISSUE TITLE
Angular 10 -  'ModuleWithProviders<T>' requires 1 type argument(s)

### ISSUE THREAD

**Issue by Stan92** [Stabzs/Angular2-Toaster#211]
Hi,
I m blocked with Angular 10  (using angular2-toaster v8.0.0)

I get this error : 
ERROR in node_modules/angular2-toaster/src/toaster.module.d.ts:3:23 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

**Comment by vamidi** [comment]
Also blocked over here

**Comment by Stabzs** [comment]
This has been published as version 10.0.0.   Thanks for being so patient!
