### ISSUE TITLE
Getting  Error: SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by nickraphael** [Stabzs/Angular2-Toaster#22]
Hi,
I've done the basic steps to install the toaster...

1.  npm install angular2-toaster
2. Add the css.
3. import {ToasterContainerComponent, ToasterService} from 'angular2-toaster/angular2-toaster';
4. constructor(toasterService: ToasterService) {
        this.toasterService = toasterService;    
    }

But I get the following error...
Error: SyntaxError: Unexpected token <

**Comment by Stabzs** [comment]
In my experience that error has occurred from bad system.js mappings. Are you using system.js and what does the configuration look like?
