### ISSUE TITLE
timeout of 0 does not work

### ISSUE THREAD

**Issue by mikebm** [Stabzs/Angular2-Toaster#23]
Hello, i have tried to override the timeout for errors to make them sticky and it does not work. 

I have tried the below and no matter what, it goes away after 5 seconds.

        var toasterconfig : ToasterConfig = new ToasterConfig({timeout: {error:0 }});
        var toast : Toast = {
            type: "error",
            title: title,
            body: message,
            showCloseButton: true,
            toasterConfig: toasterconfig
        };
        
        this.toasterService.pop(toast);    

        var toast : Toast = {
            type: "error",
            title: title,
            body: message,
            showCloseButton: true,
            timeout: 0
        };
        this.toasterService.pop(toast);

**Comment by mikebm** [comment]
Apparently using -1 for timeout works, so maybe the documentation just needs to be updated?

**Comment by Stabzs** [comment]
A toastconfig.timeout property of 0 should be perfectly fine.  However, in this case you are assigning the toasterconfig directly to the toast instance, which is incorrect behavior.  It should be bound to your toaster-container.  

That said, it looks like there also may be a bug in the check for the presence of the timeout property on the toast which is incorrectly causing it to fallback to looking at the timeout defined on the toasterconfig (which if not overridden, would be the default of 5000ms).  

This explains why -1 is working whereas 0 is not.

**Comment by Stabzs** [comment]
Fixed in `0.3.2-rc.1`.
