### ISSUE TITLE
Color change proposed

### ISSUE THREAD

**Issue by friksa** [Stabzs/Angular2-Toaster#26]
This is an awesome project, but the colors can be more modern looking.  It would be nice to use the Bootstrap colors as many project integrate with it already.
http://getbootstrap.com/components/#alerts-examples

Here is my CSS hack to change the colors:
````
#toast-container > .toast-success {
    color: #3c763d;
    background-color: #dff0d8;
    border-color: #d6e9c6;
}
.toast-success .toast-close-button {
    color: #3c763d;

}#toast-container > .toast-info {
    color: #31708f;
    background-color: #d9edf7;
    border-color: #bce8f1;
}
.toast-info .toast-close-button {
    color: #31708f;

}#toast-container > .toast-warning {
    color: #8a6d3b;
    background-color: #fcf8e3;
    border-color: #faebcc;
}
.toast-warning .toast-close-button {
    color: #8a6d3b;
}

#toast-container > .toast-error {
    color: #a94442;
    background-color: #f2dede;
    border-color: #ebccd1;
}
.toast-error .toast-close-button {
    color: #a94442;
}

.toaster-icon {
    filter: invert(0.5);
}
#toast-container > div {
    opacity: 1;
    border: 1px solid transparent;
    border-radius: 4px;
}
````

**Comment by Stabzs** [comment]
Thank you providing an example. I am not convinced that it is the responsibility of the library to provide additional color schemes as this only adds bloat. I'd need a compelling reason to introduce more overhead when it can be overridden so easily as you described.

**Comment by friksa** [comment]
Completely agree.  My proposal is not to add multiple schemes, but to change the only scheme to improve the initial experience for the user to an even better one.

**Comment by Stabzs** [comment]
When it is a single color scheme, "better" is largely subjective. With the bootstrap theme alerts, pastel is in vogue and they are not nearly as prominently featured.  That may be desirable but it also might not be.  In either case the change proposed is based entirely on subjective preference.

**Comment by friksa** [comment]
Absolutely agree.  It is subjective and it is your call whether most people will prefer the  bootstrap color scheme or not.
