### ISSUE TITLE
Need a programmatic way to remove a toast

### ISSUE THREAD

**Issue by friksa** [Stabzs/Angular2-Toaster#28]
toasterService.pop returns a toast object.

I need a way to close / remove that toast at a later time when it is not applicable anymore.  There might be multiple toasts displayed, but I need to remove a specific item.

For example, the toast may indicate that someone is requesting that their microphone is opened, but then change their mind.  So it is important to remove the toast when it is not valid anymore.

**Comment by Stabzs** [comment]
I might be missing something, but `toasterService.clear` does precisely this.

    `clear(toastId?: string, toastContainerId?: number)`

Since you have the returned toast object, whenever you need to remove the toast, use that object's parameters to call clear.

    ````Typescript
    var toast = toasterService.pop();
    toasterService.clear(toast.toastId, toast.toastContainerId); 
    ````

**Comment by friksa** [comment]
Awesome!  That was not documented on the github README.

**Comment by Stabzs** [comment]
You are absolutely right, it is not! My apologies for that oversight.  

I'll make sure to add an example in the near future.  Thank  you for pointing it out.
