### ISSUE TITLE
Custom image on toast

### ISSUE THREAD

**Issue by theunreal** [Stabzs/Angular2-Toaster#29]
As I've checked in the inspiration example located at http://codeseven.github.io/toastr/demo.html,
using <img src=""> inside the toast content shows an image. While I've been trying to do that in this module, I got the following:
![image](https://cloud.githubusercontent.com/assets/6171883/15931938/690b642c-2e62-11e6-89b4-c7ea437eb368.png)

Is there any option to implement images in a toast or this feature is not yet implemented?

**Comment by Stabzs** [comment]
Most likely you are using the default `BodyOutputType`.  You can render html (which is all you are doing here) by using the `BodyOutputType.TrustedHtml` option.  (see https://github.com/Stabzs/Angular2-Toaster#body-output-type)

If you so desired, you could also build this into a reusable component via `BodyOutputType.Component`, but that is probably overkill for this scenario.

**Comment by theunreal** [comment]
Hey @Stabzs , I've been trying to use it but the toast show only title without any body. Tried it with the example..
```
import {BodyOutputType} from 'angular2-toaster/angular2-toaster';
var toast : Toast = {
    type: 'error',
    title: 'Title text',
    body: '<h4>Body text</h4>',
    bodyOutputType: BodyOutputType.TrustedHtml
};

this.toasterService.pop(toast);
```

All I see is "Title text"

**Comment by Stabzs** [comment]
@theunreal What version are you using?

**Comment by theunreal** [comment]
Thank you, I have used an old version of this module. It works great.
