### ISSUE TITLE
Exception when calling ngOnDestroy

### ISSUE THREAD

**Issue by yiqingj** [Stabzs/Angular2-Toaster#3]
When I navigate away from the component app throws exception complaining dispose() function is undefined:

EXCEPTION: TypeError: this.addToastSubscriber.dispose is not a function. (In 'this.addToastSubscriber.dispose()', 'this.addToastSubscriber.dispose' is undefined)

here is the code location:
https://github.com/Stabzs/Angular2-Toaster/blob/master/src/toaster-container.component.ts#L219

btw thanks for putting up this awesome project!

**Comment by Stabzs** [comment]
Great catch!  I was using the pre RXJs 5 syntax.  Future tests will catch those issues :).  

Glad to hear you're enjoying it so far!
