### ISSUE TITLE
No Directive annotation found on ToasterContainerComponent

### ISSUE THREAD

**Issue by jFensch** [Stabzs/Angular2-Toaster#31]
Upgrading to Angular 2 rc.2 causes me to start getting the following error.  

Reproduced in new clone of https://github.com/AngularClass/angular2-webpack-starter when following the _Getting Started with Default Configuration_ instructions.

**Comment by Stabzs** [comment]
Angular2-Toaster is not yet upgraded to rc.2.  Thank you for reporting, I'll investigate.

**Comment by angusoid** [comment]
Same issue here

**Comment by justme1** [comment]
same issue here

**Comment by Stabzs** [comment]
Could you please provide an example of your webpack config?

**Comment by jFensch** [comment]
So the issue at hand is the your referencing a specific release of
Angular.  Currently, when your package is restored from npm, @angular/*
RC.2 is dropped into node_modules of angular2-toaster.  Perhaps a better
solution is updating package.json to depend on ^2.0.0-rc.X so that the
Angular dependencies can float as consumers of this package upgrade.

Regarding webpack.config - refer to comment when I opened the issue.

**Comment by Stabzs** [comment]
@jFensch that's a reasonable solution.  I'm assuming that justme1 has run into the issue due to the RC 3 update.  I'll apply this change to the RC.3 update for angular2-toaster.

**Comment by justme1** [comment]
@Stabzs indeed - solution suggested sound decent.

Thanks
