### ISSUE TITLE
Template Parse Errors

### ISSUE THREAD

**Issue by JayKan** [Stabzs/Angular2-Toaster#34]
![template_parse_errors](https://cloud.githubusercontent.com/assets/1400300/16213731/89f379ca-3706-11e6-943d-6e785fdd6bce.png)

Any ideas on how to resolve this? 

This template parse error is from `ToastComponent`@7:16

Thanks a lot for your help!

Cheers,
Jay Kan

**Comment by Stabzs** [comment]
It looks like you're using the latest version without using angular 2.0.0-RC.2. If you need to use rc1 please downgrade angular2-toaster to 0.3.4-RC.1.

**Comment by JayKan** [comment]
@Stabzs,

I'm actually running on RC1, let me try to update to angular2-toaster@0.3.4-RC.1 to see if I get those errors resolved.

**Comment by JayKan** [comment]
@Stabzs,

After downgrading to angular2-toaster@0.3.4-RC.1, it works like a charm, thanks for your help!

Cheers,
Jay Kan

**Comment by Stabzs** [comment]
No problem!
