### ISSUE TITLE
Can't load angular-toaster with default angular.io "Getting started" html

### ISSUE THREAD

**Issue by varadero** [Stabzs/Angular2-Toaster#4]
Hello,

I have followed angular.io "Get started" guide which notes the following SystemJS usage in index.html:
```html
    <script>
      System.config({
        packages: {        
          app: {
            format: 'register',
            defaultExtension: 'js'
          }
        }
      });
      System.import('app/main')
            .then(null, console.error.bind(console));
    </script>
```

With that configuration I built fairly simple working code. Unfortunately, when I try to use angular2-toaster (I have created node_modules/angular2-toaster folder and copy/paste "lib" folder as well as angular2-toaster.js file), I don't know how to change that script in order to load it. I tried to add "map" property as seen in your demo\index.html with no success:
```html
        System.config({
            packages: {
                app: {
                    format: "register",
                    defaultExtension: "js"
                }
            },
            map: {
                'angular2-toaster': 'node_modules/angular2-toaster'
            }
        });
        System.import('app/main')
              .then(null, console.error.bind(console));
```

What happens is that I can see the browser makes request to ```http://localhost/node_modules/angular2-toaster/angular2-toaster``` with no ".js" extension which fails.

Could you explain how to load angular2-toaster by using angular.io default index.html SystemJS usage ?

**Comment by Stabzs** [comment]
A few notes first.

I highly recommend always installing as a node module directly via npm install.  It seemed as if you weren't and that could create folder hierarchy issues within the package itself if you copy them incorrectly.

The main difference between your setup with or without the map in comparison to my systemjs demo is that you have declared a package.  Once you declare a package, you are essentially declaring another root path which is placing the mapped angular2-toaster node module outside of the expected path.  You could fix this bymoving up a directory for your module inclusion when mapping:

```js
System.config({
            packages: {
                app: {
                    format: "register",
                    defaultExtension: "js"
                }
            },
            map: {
                'angular2-toaster': '../node_modules/angular2-toaster'
            }
        });
        System.import('app/main')
              .then(null, console.error.bind(console));
```

**Comment by Stabzs** [comment]
Please see the new, additional demo that I added.  The package needs to be mapped AND make sure that you are setting your tsconfig.json build option to system, not commonjs as I was in the original systemjs demo (which still shows how you can manually map commonjs builds via systemjs).
