### ISSUE TITLE
route navigate after pop

### ISSUE THREAD

**Issue by emalmbor** [Stabzs/Angular2-Toaster#40]
I have a situation where I issue the pop, and then issue a route navigate.  The toast message doesn't display with the route.  When I remove the route it works. Any ideas how to get around this?

**Comment by Stabzs** [comment]
How is the container related to the routable views?  Is it located outside of the router?

**Comment by emalmbor** [comment]
Thanks for your reply!  It turns out we’re changing our routing.  I’ll let you know if the problem goes away after the change. Thanks again!

**Comment by Stabzs** [comment]
You're welcome!  I'll close this for now but if it is still an issue after your routing changes, please feel free to reopen the issue.
