### ISSUE TITLE
Add removedToast observable

### ISSUE THREAD

**Issue by CaselIT** [Stabzs/Angular2-Toaster#42]
First of all thanks for this useful library!

It would be nice to have an observable in the `ToasterService` which notifies when a toast has been removed, regardless of the reason. It would the opposite of the `addToast` observable

I you like I could make a pr with this feature.

**Comment by CaselIT** [comment]
Any update @Stabzs ?

**Comment by Stabzs** [comment]
Thanks for the feedback and the request!

Absolutely, I can see the value in this. What would be broadcasted would be the toastId and the containerId. There is obviously a case where multiple events would be broadcasted for a toast that exists in multiple containers. I can look at adding this soon.

**Comment by CaselIT** [comment]
Great, Thanks.

**Comment by Stabzs** [comment]
@CaselIT I haven't had time to get to this yet.  If you are interested in creating a PR with tests, it would definitely help get this completed sooner :).  Else I'll get to it when I can.

**Comment by CaselIT** [comment]
I'll look into it.
Thanks

**Comment by Stabzs** [comment]
Since there hasn't been a lot of traction on this particular request, it doesn't seem to be that large of a demand.  Closing.
