### ISSUE TITLE
Bundle? Package?

### ISSUE THREAD

**Issue by EricSch** [Stabzs/Angular2-Toaster#43]
Hi, thanks for this component. 
Seems to be useful.
But as it is, we can't use is, because it is missing a package / bundle, which we could easily include in our project. We aren't using Webpack and we aren't deploying Node modules. 

Would be great, thanks.

**Comment by Stabzs** [comment]
Happy to provide it.

How are you building your Angular2 apps today if not with a module loader?  Are you using the cli or systemjs?

**Comment by EricSch** [comment]
Thank you!
with gulp we grab and package all the files necessary for deployment and are loading them via systemjs. Tried webpack, but didn't work like we needed.

**Comment by Stabzs** [comment]
Thanks for the clarification!

SystemJS should work fine as long as you use gulp to include the entire lib directory.  I'm hesitant to add a concatenated file since it is deliberately built to allow repacking by whatever module loader is chosen for a project.  Including an additional file would just add more bloat to the package for nearly all use cases.

**Comment by EricSch** [comment]
Yes, this was my first try. But didn't work for me. All my other includes have System.registerDynamic wrapper around the function body, but this is missing in the lib files.
I could try to add them as package via SystemJS like the angular files. But this means, I have to copy always all the files in a separate directory, and can't bundle and minimize them.

So it would be really helpful to have a bundled self-registering file.
Thanks for your help and time :)

**Comment by Stabzs** [comment]
@EricSch sorry for the lengthy delay on this issue.

Adding additional tooling to support minification doesn't currently seem to be common in the Angular 2 plugin ecosystem.  In addition, it would add additional complexity to the build and maintenance process for the library.

In an effort to make consumption easier, I've added a very simple bootstrapped plunker demo that may provide additional direction https://github.com/Stabzs/Angular2-Toaster#demo.
