### ISSUE TITLE
please, add online demo or a plunker example.

### ISSUE THREAD

**Issue by yahyaKacem** [Stabzs/Angular2-Toaster#46]

**Comment by jtc10005** [comment]
the plunker appears to be broken
[http://plnkr.co/edit/hkENUhos6q9fhiOHprXO?p=preview](http://plnkr.co/edit/hkENUhos6q9fhiOHprXO?p=preview)

**Comment by Stabzs** [comment]
@jtc10005 this has been updated to `0.5.2-rc.7` and functionality is restored.
