### ISSUE TITLE
Update to angular RC5 ?

### ISSUE THREAD

**Issue by gvsdan** [Stabzs/Angular2-Toaster#47]
I don't know if maybe we need to update toaster in to a module?

**Comment by bernhard-niedermayer** [comment]
see #48

**Comment by gvsdan** [comment]
Ok. i'm goin to close this issue

**Comment by Stabzs** [comment]
This is now published to NPM under version `0.3.6-rc.5`.

**Comment by gvsdan** [comment]
@Stabzs  thanks

**Comment by Stabzs** [comment]
@gvsdan You're welcome. There was a missing file in the above published version. Please use 0.4.0-rc.5.
