### ISSUE TITLE
0.3.6-rc.5 not published to NPM

### ISSUE THREAD

**Issue by kreed-rmn** [Stabzs/Angular2-Toaster#49]
The current documentation for this module indicates the current version is 0.3.6-rc.5, however that version is not published to the public NPM registry. 

Can this be published to NPM?

**Comment by Stabzs** [comment]
This was pending a documentation change around NgModule inclusion, which has been added. 

This is now published to NPM under version `0.3.6-rc.5`.

**Comment by kreed-rmn** [comment]
@Stabzs Looks like 0.3.6-rc.5 is missing the toast.module module. 


ERROR in ./~/angular2-toaster/angular2-toaster.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./lib/toast.module in ~/src/main/webapp/node_modules/angular2-toaster
 @ ./~/angular2-toaster/angular2-toaster.js 7:22-51

**Comment by Stabzs** [comment]
Correct, it is.  The package was improperly built before publishing.

Please upgrade to last night's new build 0.4.0-rc.5.  It includes the toast.module, but it also renames the toast.module to toaster.module to be more consistent with the rest of the top-level APIs.
