### ISSUE TITLE
Angular2-Toaster installs own version of Angular 2

### ISSUE THREAD

**Issue by bobrosoft** [Stabzs/Angular2-Toaster#50]
Hi there!
Can you tell me why Angular 2 and RxJS is in "dependencies" instead of "peerDependencies" as it should be? Angular2-Toaster goes as a "plugin", not standalone service, right? Check https://github.com/valor-software/ng2-bootstrap/blob/development/package.json for example.

**Comment by Stabzs** [comment]
There are plans to move these dependencies to peerDependencies per the conversation in #48. However, currently peerDependencies breaks the Karma test shim configuration. Once that is patched, the dependencies will be updated to peerDependencies. 

Thanks for raising this issue. This is an important priority and something that needs to change in the very near future.
