### ISSUE TITLE
Incompatible with RC.6

### ISSUE THREAD

**Issue by dagstuan** [Stabzs/Angular2-Toaster#52]
The package is currently incompatible with RC.6 of Angular 2 due to the removal of `ComponentResolver` and the renaming of `DomSanitizationService` to `DomSanitizer`

**Comment by klaascuvelier** [comment]
@Stabzs thanks for the quick fix. 
Seems to work fine now, but the build fails

**Comment by Stabzs** [comment]
Yes there are issues getting the upgraded tests and test structure to build on CI, although they run correctly locally and coverage remains at 100%. I felt it was more important to deliver RC6 functionality than to hold off working on CI. Corrections to the test build will be added soon.
