### ISSUE TITLE
Update to Angular2 RC7

### ISSUE THREAD

**Issue by ElsewhereGames** [Stabzs/Angular2-Toaster#59]
Angular2 RC7 has been released, but I think you only have to bump the version number of RxJS to ```5.0.0-beta.12```.

**Comment by Stabzs** [comment]
Thank you for the head's up!  This will get pushed soon.

**Comment by ElsewhereGames** [comment]
Thank you for this awesome library!

I noticed that even Material2 has not updated yet to the new RC, I don't think anyone was expecting a new one this quick.

**Comment by Stabzs** [comment]
@ElsewhereGames  you're welcome!  Glad you're finding it useful!

This is now published as `.0.5.2-rc.7`.
