### ISSUE TITLE
Webpack question

### ISSUE THREAD

**Issue by AlexZhidkov** [Stabzs/Angular2-Toaster#6]
Hi, I'm new to webpack can you tell me how to link your scc using webpack?

**Comment by Stabzs** [comment]
I don't use webpack myself so I'm probably not the best resource.  However, regardless of how you "pack" and deliver your source, the consumption of the library should be the same.  You'd want to install the package and import what you need from the `angular2-toaster` module file:

import {ToasterContainerComponent, ToasterService} from 'angular2-toaster/angular2-toaster';

**Comment by AlexZhidkov** [comment]
Thank you for the answer and your library.

**Comment by sagarjumble** [comment]
Hey it throws error using web pack .
Error  zone.js:269 Uncaught Can't resolve all parameters for ToastComponent: (?, ComponentFactoryResolver).

**Comment by Stabzs** [comment]
@sagarjumble it appears to be failing on the `private sanitizer: DomSanitizer` constructor parameter for `ToastComponent`.  This is included via `'@angular/platform-browser'`.  Make sure you are loading it appropriately in your web pack configuration.

**Comment by sagarjumble** [comment]
@Stabzs I am loading the platform browser  using
import { BrowserModule } from '@angular/platform-browser'
Is there any other issues.

**Comment by Stabzs** [comment]
It is impossible to say without a reproduction of the issue. It can't resolve the injection so something must not be loaded correctly. Make sure that you are using all 2.0.0-rc.6 angular packages.

**Comment by sagarjumble** [comment]
I am using rc.5

**Comment by sagarjumble** [comment]
Trying to Utilize it in https://github.com/akveo/ng2-admin.git
Above project

**Comment by Stabzs** [comment]
@sagarjumble `angular2-toaster@0.5.0-rc.6` and later requires peer dependencies of angular 2 `2.0.0-rc.6` or higher.  They renamed the DOM sanitization service, which is why your injection is failing.  Please either degrade angular2-toaster to an rc.5 compatible version (not recommended) or upgrade to angular 2 rc.6.

**Comment by sagarjumble** [comment]
Can you provide me a link which will help me to upgraded to rc6

**Comment by Stabzs** [comment]
@sagarjumble you can take a look at something like the following: http://proudmonkey.azurewebsites.net/upgrading-from-angularjs-2-beta-to-rc-6/.  I highly recommend you read the changelog for rc6 as there are a large number of breaking changes.
