### ISSUE TITLE
Missing `angular2-toaster.ts` in repository

### ISSUE THREAD

**Issue by BrainCrumbz** [Stabzs/Angular2-Toaster#60]
Hi there. *package.json* states that project entry point is given by

```json
"main": "angular2-toaster.ts",
```

but then, there's no such file in repository root. Instead you can find its *js*, *js.map*, *d.ts* cloned counterparts there:

![angular2-toaster-ts](https://cloud.githubusercontent.com/assets/3185573/18533607/947ad696-7ae4-11e6-9cbf-649ff8d9f3e9.png)

**Comment by Stabzs** [comment]
Great catch!  The `.ts` file was swapped out a long time ago since it really didn't _need_ to be compiled.  I'll update the package.json file and this will go in the next build.

**Comment by BrainCrumbz** [comment]
Actually, shouldn't those build output files be also deleted and ignored from source control?

**Comment by Stabzs** [comment]
No, because these are entry points that need to be modified if the module changes.  They do belong in source control.

That said, yes, the typings directory **_can_** be removed from source control, but it is referenced via tsd.json.  I don't think that removing it has a strong enough argument currently since typings are used in builds and tests.

**Comment by BrainCrumbz** [comment]
Of course those file are there for some reason. Was just questioning whether they could be generated, hence being output of some tool, as opposed to "manually edited" sources.

1. Aren't `angular2-toaster.d.t.s| .js| .js.map` recreated upon each build?
1. Isn't `typings\` folder recreated during some install/postinstall phase, so already existing for every build?

E.g. for our projects, `typings\` comes from this bit in *package.json*:

```json
"postinstall": "npm run install-typings",
   "install-typings": "typings install",
```

Anyway, just questioning. Feel free to close this issue when more appropriate! 👍

**Comment by Stabzs** [comment]
1.  They are currently not, although somewhere on the back of my deprioritized list is a task to move them back into the build.  It would be far more correct to do so.  Once that happens yes, then only the source would need to be checked in.  It just isn't at that point atm.

2.  The typings folder is not currently recreated during install/postinstall, although it's an excellent suggestion.   I'll look at incorporating it into the build process.  Once done, yes, absolutely, the typings folder can be removed :).

Thanks for the suggestions!  They're very appreciated!
