### ISSUE TITLE
Unable to redirect to another page using pop/popTo.

### ISSUE THREAD

**Issue by krunaldesai79** [Stabzs/Angular2-Toaster#61]
I am not able to redirect to another page after executing the code to  show the message using pop.

this.toast = {
                type: 'success',
                body: 'Hello',
                showCloseButton: false,
                timeout: 2000                  
            };
this.toasterService.pop(this.toast);

I have tried below  both option to redirect to another page but didn't get success.

this.nav.popTo(this.nav.getByIndex(this.viewCtrl.index - 2))
setTimeout(() => this.nav.popTo(this.nav.getByIndex(this.viewCtrl.index - 2)), 2100);

Please help me on this issue. It is very urgent.

**Comment by Stabzs** [comment]
This has nothing to do with the toaster library.  That said, if you create a plunker that demonstrates the issue, I'll be happy to take a look.
