### ISSUE TITLE
Hanging ngModule in container specs?

### ISSUE THREAD

**Issue by BrainCrumbz** [Stabzs/Angular2-Toaster#64]
In *toaster-container.component.spec.ts*, [after TestComponent class](https://github.com/Stabzs/Angular2-Toaster/blob/56d040b1ab30cfd986fa320e68b2cb62b60899e5/src/toaster-container.component.spec.ts#L28) there seems to be a `@NgModule` decorator not attached to any class definition:

```ts
export class TestComponent {
    toasterService: ToasterService;

    constructor(toasterService: ToasterService) {
        this.toasterService = toasterService;
    }

    public toasterconfig: ToasterConfig = new ToasterConfig({ showCloseButton: true, tapToDismiss: false, timeout: 0, toastContainerId: 1 });
    public toasterconfig2: ToasterConfig = new ToasterConfig({ showCloseButton: true, tapToDismiss: false, timeout: 0, toastContainerId: 2 });
}
@NgModule({
    imports: [ToasterModule],
    declarations: [TestComponent]
})


// Mock component for testing bodyOutputType Component rendering
@Component({
    selector: 'test-dynamic-component',
    template: `<div>loaded via component</div>`
})
```

Is that intended? While working at a PR to remove typings from source control, we incurred in a build error on *toaster-container.component.spec.ngfactory.ts*: 

> Error: Error at D:/WS/JS/Angular2-Toaster/src/toaster-container.component.spec.ngfactory.ts:97:14: Cannot redeclare block-scoped variable 'TestDynamicComponentNgFactory'.
Error at D:/WS/JS/Angular2-Toaster/src/toaster-container.component.spec.ngfactory.ts:361:14: Cannot redeclare block-scoped variable 'TestDynamicComponentNgFactory'.
    at check (D:\WS\JS\Angular2-Toaster\node_modules\@angular\tsc-wrapped\src\tsc.js:31:15)
    at Tsc.typeCheck (D:\WS\JS\Angular2-Toaster\node_modules\@angular\tsc-wrapped\src\tsc.js:86:9)
    at D:\WS\JS\Angular2-Toaster\node_modules\@angular\tsc-wrapped\src\main.js:33:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:577:11)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
Compilation failed

Not sure if it's due to this issue, though.

**Comment by BrainCrumbz** [comment]
Adding the following fixes build:

```ts
@NgModule({
    imports: [ToasterModule],
    declarations: [TestComponent]
})
export class ComponentSpecModule { }  // <-- added
```

but not sure what happens to tests then...

> Chrome 53.0.2785 (Windows 10 0.0.0) ERROR: '(SystemJS) XHR error (404 Not Found) loading http://localhost:9876/base/node_modules/@angular/core/bundles/core.umd.js/src/linker/ng_module_factory
        Error: XHR error (404 Not Found) loading http://localhost:9876/base/node_modules/@angular/core/bundles/core.umd.js/src/linker/ng_module_factory
            at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?02524aa211d9378ad861942509a2e2b9e3622f53:628:29)
            at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?02524aa211d9378ad861942509a2e2b9e3622f53:225:37)
            at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?02524aa211d9378ad861942509a2e2b9e3622f53:125:47)
            at XMLHttpRequest.ZoneTask.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?02524aa211d9378ad861942509a2e2b9e3622f53:293:33)
        Error loading http://localhost:9876/base/node_modules/@angular/core/bundles/core.umd.js/src/linker/ng_module_factory as "@angular/core/src/linker/ng_module_factory" from http://localhost:9876/base/lib/toaster-container.component.spec.ngfactory.js'

**Comment by Stabzs** [comment]
Yes, this is absolutely intended.  This is the NgModule definition for the TestComponent class (hence the TestComponent declaration).  Removing or modifying this will break the tests, as you found.

**Comment by Stabzs** [comment]
The issue here is that there needed to be a declared exported class for TestComponent as well.
