### ISSUE TITLE
typings are still required

### ISSUE THREAD

**Issue by reflog** [Stabzs/Angular2-Toaster#67]
you latests build 1.0.0 even though you removed typings, still calls it. so it errors with:

sh: 1 typings not found

**Comment by jbrekle** [comment]
same here, my build fails and even a globally installed typings does not hlp. Either remove it (I am not sure if you want it, there was some back-and-forth in the package.json postinstall) or use a approach discussed [here](https://github.com/ghpabs/angular2-seed-project/issues/54) to use the locally installed typings executable

**Comment by Stabzs** [comment]
Sorry I'm not following. The first step for pulling down the package as source should always be to re-run npm install. Is this still failing after doing so?  If so I think that the dep just needs to be updated to use the global flag.

**Comment by reflog** [comment]
postinstall shouldn't run typings, since you are now using @types approach... (if i'm not mistaken)

**Comment by Stabzs** [comment]
The @types approach is for the angular packages. However, the jasmine tests still require core-js and jasmine typings to compile and execute correctly, some some form of typings are still needed for them, as far as I know. 

That said, if you are aware of another approach, please let me know. Could you also verify if installing the typings package with the global flag resolves the issue?

**Comment by reflog** [comment]
yes, global install fixes it. if you do need it for jasmine, the solution would be to return it to devDependencies...

**Comment by Stabzs** [comment]
One again I'm not sure if I follow you.  It is currently listed in devDependencies.  Did you by chance pull down one of the checked in in-between versions while it was in flux?  That said, I do completely agree with you...it SHOULD be a devDependency.

**Comment by reflog** [comment]
That IS super weird! :) I installed 1.0.0 ... And I just peeked inside - it IS mentioned in devDependencies. Very odd. But I tried it again - same result. Postinstall fails.

**Comment by jbrekle** [comment]
Is it possible that there is a difference between npm installing within a angular2-toaster cjkecked out repo  vs. letting npm install angular2-toaster as a dependency?
I tried to install typings globally on our buildagent but it does not work
```
[14:17:33][Step 4/14] > MyProject@1.0.0 preinstall C:\TeamCity\buildAgent\work\45773c1387d37fae\sources\BSite2.Frontend.Web.Angular2
[14:17:33][Step 4/14] > npm i typings -g
[14:17:42][Step 4/14] C:\Users\SA-CID-TcSvcUser\AppData\Roaming\npm\typings -> C:\Users\SA-CID-TcSvcUser\AppData\Roaming\npm\node_modules\typings\dist\bin.js
[14:17:42][Step 4/14] typings@1.3.3 C:\Users\SA-CID-TcSvcUser\AppData\Roaming\npm\node_modules\typings
...
[14:17:56][Step 4/14] > angular2-toaster@1.0.0 postinstall C:\TeamCity\buildAgent\work\45773c1387d37fae\sources\MyProject\node_modules\angular2-toaster
[14:17:56][Step 4/14] > typings install
[14:17:56][Step 4/14] 'typings' is not recognized as an internal or external command, operable program or batch file.

```

**Comment by Stabzs** [comment]
@reflog so reading the thread that @jbrekle linked, it would _**appear**_ that there is no longer a bin folder in the typings package either, meaning no executable.  It is odd that it isn't working as a devDependency however.

**Comment by Stabzs** [comment]
@jbrekle it is possible, though I'd need to understand your scenario more.  Are you pulling down the angular2-toaster npm package via npm and then rebuilding it?  Because you wouldn't want to do that.  The distributed source is already compiled via ngc.  You would just want to wire in the files and allow your module loader to perform tree shaking as necessary.

However, when building it from checked out source, it SHOULD be working.  The travis-ci build installs it from devDependencies and it picked up the typings install step of the build marvelously:  https://travis-ci.org/Stabzs/Angular2-Toaster/builds/160349118.
 
That said, I think I now see the problem.  I was under the incorrect impression from the pull request that sparked all this that the postinstall hook was called after just the npm install command for the package, not that it would be called on ALL installs period.

If that is indeed the case, then yes, this absolutely would cause problems and needs to be moved to a different hook (such as pre build).

I'll make the changes shortly and push a new version.  Thanks for the report and sorry for the pain and confusion.

**Comment by jbrekle** [comment]
@Stabzs umh, we use the npm package, and as far as there are only ts file in there, I assume we then compile it into our bundles. Never thought of that. Can you give me a hint about ngc?

**Comment by Stabzs** [comment]
@jbrekle ngc is the `@angular/compiler-cli` package that enables Ahead of Time compilation.  `angular2-toaster` was switched over to it to enable your applications to use AoT compilation if you so desire.  You by no means have to, but the support is there if you need.

That said, I've tested my theory locally and that does indeed seem to be the problem...it never should have been calling `typings install` in the postinstall hook, whereas the prebuild hook does exactly what is needed when building the source (which is not what you are doing). I'll be pushing version 1.0.1 shortly with the fix.

**Comment by Stabzs** [comment]
This has been published to npm as `1.0.1`.  Again, sorry for the confusion and thank you for pointing out the issue quickly!

**Comment by jbrekle** [comment]
its working now! thanks, for the fast reply!

**Comment by reflog** [comment]
awesome, thanks!

**Comment by Stabzs** [comment]
@jbrekle thanks for the confirmation and you're welcome!

@reflog  You're welcome!
