### ISSUE TITLE
Compile *.metadata.json files with ngc and include in library

### ISSUE THREAD

**Issue by isaacplmann** [Stabzs/Angular2-Toaster#68]
angular2-toaster does not ship with *.metadata.json files next to the *.d.ts files.  This is needed for AoT compiled apps ([reference](https://github.com/angular/angular/issues/11262#issuecomment-244472000)).

I've written up [an article](https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.qg0xq01pr) with steps to generate those files.  I'll make a PR, if I find time.

**Comment by Stabzs** [comment]
This is incorrect.  What version of the package are you looking at?  The metadata.json files absolutely ship with the d.ts files:

![image](https://cloud.githubusercontent.com/assets/11450848/18885107/78e3f44a-84a7-11e6-99a4-20226d015921.png)

**Comment by isaacplmann** [comment]
You're right.  Sorry.  Good work.

**Comment by Stabzs** [comment]
@isaacplmann  no problem, I appreciate you being diligent!
