### ISSUE TITLE
CSS Class Names Conflict with Boostrap

### ISSUE THREAD

**Issue by alexandria122** [Stabzs/Angular2-Toaster#69]
The Bootstrap css stylesheet has the same naming convention for toast-error, toast-info, etc., with its own image icons.  So anyone with Bootstrap imported into their project will have funky results when showing a toast.

**Comment by Stabzs** [comment]
This would be caused by a lack of specificity on Bootstrap's part. Loading toaster.css before bootstrap should reoslve this.  It isn't exactly related to the angular2-toaster library itself.
