### ISSUE TITLE
Cant run any of your code: exports not defined

### ISSUE THREAD

**Issue by d1820** [Stabzs/Angular2-Toaster#7]
Trying to run your component and get this error right from app start:

```
i get exports not defined:

exports.BodyOutputType = require('./lib/bodyOutputType').BodyOutputType;
exports.Toast = require('./lib/toast').Toast;
exports.ToasterConfig = require('./lib/toaster-config').ToasterConfig;
exports.ToasterContainerComponent = require('./lib/toaster-container.component').ToasterContainerComponent;
exports.ToasterService = require('./lib/toaster.service').ToasterService;
```

I am including your script in a combined output script named common.js
it is bundled with the following scripts

```
 createLibFolderObj("systemjs", "systemjs/dist/system.src.js"),
        createLibFolderObj("angular2", "angular2/bundles/angular2.dev.js"),
        createLibFolderObj("angular2", "angular2/bundles/router.dev.js"),
        createLibFolderObj("angular2", "angular2/bundles/http.dev.js"),        
        createLibFolderObj("rxjs", "rxjs/bundles/Rx.js"),
        createLibFolderObj("toastr", "angular2-toaster/angular2-toaster.js")
```

Any ideas what could be wrong. from the limited examples provided i have eveything setup as suggested.

My current versions are:
```
 "angular2": "^2.0.0-beta.11",
        "bootstrap": "^3.3.6",
        "es6-promise": "^3.1.2",
        "es6-shim": "^0.35.0",
        "font-awesome": "^4.5.0",
        "reflect-metadata": "0.1.3",
        "rxjs": "^5.0.0-beta.3",
        "systemjs": "^0.19.24",
        "zone.js": "^0.6.5",
        "angular2-toaster": "0.1.0-beta.2"
```

**Comment by Stabzs** [comment]
How are you mapping angular2-toaster?  Are you using typescript or are you using another transpiler?  Also, if you could provide a small, working example of the problem (gist, fiddle, plunkr, etc), that would be helpful.

Thanks!

**Comment by d1820** [comment]
I am using typescript calling:

Component looks like:
```
import {Injectable} from 'angular2/core';
import {ToasterService} from 'angular2-toaster';

@Injectable()
export class NotificationService {
       constructor( private _toasterService: ToasterService) {
    }

    error(message: string) {
        this._toasterService.pop("error","Error",message);        
    }
    info(message: string) {
        //this._toasterService.pop("info", "Information", message);
    }
    success(message: string) {
        //this._toasterService.pop("success", "Success", message);
    }
    warn(message: string) {
    //    this._toasterService.pop("warn", "Warning", message);
    }
}
```

I add  ToasterContainerComponent to the root app component and add that to the directives and the ToasterService to providers

in my gulp tasks i take your angular2-toaster/angular2-toaster.js and combined it into 1 common.js file that contains all third party components.

I am wondering if its the version of typescript or angular? What version of angular.beta is this confirmed to work with?

Thanks

**Comment by Stabzs** [comment]
As of today, angular2-toaster has been updated to use `"angular2": "^2.0.0-beta.12",`.

I'm confused on your process.  Your import statement doesn't match your combination script.  If you moved away from combining a new export and instead setting up a map in systemjs, your import would be:

```typescript
import {ToasterService} from 'angular2-toaster/angular2-toaster';

@Injectable()
export class NotificationService {
```

Aside from your import statement being incorrect, it seems that your actual issue is not in importing the service, but rather in combining the module into your own module.  It seems like export just simply isn't defined.  Are you loading a proper module loader beforehand?  Finally, what gulp library are you using for combining the files?  I'm not familiar with `createLibFolderObj`.

**Comment by d1820** [comment]
Everything compiles and runs, aside from this control.

I am using SystemJs with Typescript. I moved your file out on its own so its not part of the concatenated js file group any more.

I still get the same error.
looks like it may be related to: https://github.com/frankwallis/plugin-typescript/issues/47

for the gulp concatenating im using
 require("gulp-concat") which is taking the angular2-toastr js and a couple other js files and putting them together.

Thanks for the responses

**Comment by Stabzs** [comment]
Are you able to put together a small example that reproduces the issue?  I haven't been able to reproduce what you're seeing and if the export syntax needs to be changed, I'd love to be able to test against all conditions.

**Comment by d1820** [comment]
I ended up taking parts of yours and the original toastr and writing my own simple version. 

Thanks for all the responses.

**Comment by Stabzs** [comment]
@d1820 Happy to try to help :)
