### ISSUE TITLE
opacity

### ISSUE THREAD

**Issue by DorBashan** [Stabzs/Angular2-Toaster#72]
any plans to configure the opacity of the toast?
something similar to "timeout" like:

`new ToasterConfig({opacity: {error:50, success:100, warning:50, info:100}});`

(the numbers are percents of course)

**Comment by Stabzs** [comment]
This doesn't need to be configured as a parameter if this is instead added as a style. Opacity feels very much like a CSS override.

**Comment by DorBashan** [comment]
Agreed, anyway I think the default opacity should be 100%

**Comment by Stabzs** [comment]
Since this originally derives from the toastr library, which used an opacity of .8, I think that the library is currently in line with community expectations. In addition, you can always override the opacity yourself if you need to change it.
