### ISSUE TITLE
After timeout toaster fades a little but doesn't fully close

### ISSUE THREAD

**Issue by quiringk** [Stabzs/Angular2-Toaster#73]
I see in your demo that the info toaster fully closes after 5000ms. When I try to use the configuration with the timeout the toaster goes from solid color, to a little faded but not fully closed. Do you know why this may be?

**Comment by Stabzs** [comment]
No I have never run into that before. Would you be able to create a plunker that reproduces the issue?  Do you have any CSS overrides?
