### ISSUE TITLE
progress bar to indicate time is up...

### ISSUE THREAD

**Issue by anrepppp** [Stabzs/Angular2-Toaster#76]
So far, i liked the features the plugin has provided. But, one thing that i feel it's missing was 'progressBar'. Please can you add the progressBar feature, since it indicates the progressing time to the user inside the toaster. It is helpful in many ways to the user to take action before toaster fades away.

Also I have a question how to customize the color of a toaster, for instance i want to change the color of the info toasters to yellow.

Thanks for your help in advance.

**Comment by Stabzs** [comment]
You are correct, a progress bar feature was never added.  I'll look into adding that as a feature.

If you want to change the color of the info toasters, simply override the css for that class.

**Comment by anvesh48** [comment]
Fantastic, that is a good new..!

**Comment by anvesh48** [comment]
@Stabzs 
Any update about the implementation of progress bar feature? Please let me know if i can help you out.

**Comment by Stabzs** [comment]
@anvesh48  sorry for the delay.  This is now the next enhancement priority.

**Comment by anvesh48** [comment]
Thanks..! :)

**Comment by anvesh48** [comment]
@Stabzs any update about progress bar feature.

**Comment by stalek71** [comment]
I started using this component also and having time elapsing indicator could be awesome :)
Do you have any info for us on a progress?

**Comment by Stabzs** [comment]
@stalek71 I have not spent any time working on this feature, my apologies.  I will try to make time to look into adding progress bars. :)

**Comment by stalek71** [comment]
Thanks for the feedback :)

**Comment by kspearrin** [comment]
Also looking for this feature since it was available in the AngularJS toastr version we were using prior.

**Comment by anthony-sap** [comment]
any progress on this?
