### ISSUE TITLE
(SystemJS) XHR error (404 Not Found) loading http://localhost:51372/angular2-toaster/angular2-toaster(…)

### ISSUE THREAD

**Issue by ajithkallur** [Stabzs/Angular2-Toaster#78]
(SystemJS) XHR error (404 Not Found) loading http://localhost:51372/angular2-toaster/angular2-toaster(…).

When I am trying to Import the Toaster Service and Toaster Module it shows up this error.

**Comment by Stabzs** [comment]
You've mis-configured your SystemJS mapping.  Please see the SystemJS demos or the online plunker for examples.  I am closing this since it is not an issue with the library, but if you create a plunker reproducing the issue I'm happy to take a look and point you in the right direciton.
