### ISSUE TITLE
Basic Usecase - No Directive annotation found on ToasterContainerComponent

### ISSUE THREAD

**Issue by afirdousi** [Stabzs/Angular2-Toaster#8]
I tried using angular2-toaster with the most simplest example. Tried exactly the way mentioned in Readme. and got the following:

I downloaded angular2-toaster from npm which gave me `0.1.0-beta.3`

Tried making a very basic use on my app.ts (my root component) as mentioned in examples on Readme.md

Getting the following:

`
EXCEPTION: No Directive annotation found on ToasterContainerComponent
`
BaseException {message: "No Directive annotation found on ToasterContainerComponent", stack: "Error: No Directive annotation found on ToasterCon…/polyfills.bundle.js:1152:2), <anonymous>:274:21)"}
`

`
Error: Uncaught (in promise): No Directive annotation found on ToasterContainerComponent
`

`
zone.ts?949c:855 Unhandled Promise rejection: No Directive annotation found on ToasterContainerComponent ; Zone: angular ; Task: Promise.then ; Value: 
`

**Comment by Stabzs** [comment]
How are you including angular2-toaster in your component?

**Comment by Stabzs** [comment]
In addition, what versions of angular and typescript are you using?

**Comment by afirdousi** [comment]
Angular 2 : `2.0.0-beta.11`
TypeScript : `1.8.9`

In my component:

`
import {ToasterContainerComponent, ToasterService, ToasterConfig} from 'angular2-toaster/angular2-toaster';
@Component({
  selector: 'app',
  providers: [ ...FORM_PROVIDERS,EventConfigServ],
  directives: [ ...ROUTER_DIRECTIVES, Dashboard, MainHeader,Navigation, SubHeader, Breadboard, CompHealth, AdminSetting ],
  pipes: [],
  styles:[],
  template: `
    <main-header></main-header>
    <navigation></navigation>
    <div id="main" role="main">

      <sub-header></sub-header>


      <div id="content">
         <main>
            <router-outlet></router-outlet>
        </main>

      </div>

 <toaster-container></toaster-container>

    </div>

  `
})
export class App {
    private toasterService: ToasterService;

    constructor(toasterService: ToasterService) {
        this.toasterService = toasterService;    
        this.toasterService.pop('success', 'Args Title', 'Args Body');
    }
}
`

**Comment by afirdousi** [comment]
I have excluded a lot of import statements which are related to my app internally, just to make this concise.

**Comment by Stabzs** [comment]
Thanks for providing the additional information.

Using `angular2-toaster-0.1.0-beta.3` and the Angular2 and Typescript versions you mentioned, I was unable to reproduce your issue.  I've created a quick gist with the main files used to attempt to recreate the issue.  Please note the tsconfig compilation options.

https://gist.github.com/Stabzs/6d002d2da4d2f7c6081805fb813ee2dd

**Comment by afirdousi** [comment]
Sure yeah i think I made a mistake copying my code over here. My toaster call was in a method and not in constructor because you are write, no DOMs until you fire ngOnInit or ngAfteViewInit .... I will defnitely check and try your gist and will get back. Thanks for your response, i appreciate it. 👍

**Comment by Stabzs** [comment]
@afirdousi happy to help.  if you need additional clarification, don't hesitate to ask :)

**Comment by webdev48** [comment]
@Stabzs Have you tried using it with webpack ? The example you have given uses System JS but when I try to compile it down with webpack it doesn't work and shows me the exact same error.

Stacktrace

`
EXCEPTION: No Directive annotation found on ToasterContainerComponent
?d41d:73 Error: Uncaught (in promise): No Directive annotation found on ToasterContainerComponent
    at resolvePromise (eval at <anonymous> (polyfills.bundle.js:1153), <anonymous>:383:31)
    at eval (eval at <anonymous> (polyfills.bundle.js:1153), <anonymous>:419:17)
    at ZoneDelegate.invokeTask (eval at <anonymous> (polyfills.bundle.js:1153), <anonymous>:204:37)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (eval at <anonymous> (vendor.bundle.js:1336), <anonymous>:35:41)
    at ZoneDelegate.invokeTask (eval at <anonymous> (polyfills.bundle.js:1153), <anonymous>:203:42)
    at Zone.runTask (eval at <anonymous> (polyfills.bundle.js:1153), <anonymous>:103:47)
    at drainMicroTaskQueue (eval at <anonymous> (polyfills.bundle.js:1153), <anonymous>:322:35)
    at HTMLDocument.ZoneTask.invoke (eval at <anonymous> (polyfills.bundle.js:1153), <anonymous>:274:21)
zone.ts Unhandled Promise rejection: No Directive annotation found on ToasterContainerComponent ; Zone: angular ; Task: Promise.then ; Value:

`

**Comment by webdev48** [comment]
My tsconfig.json

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true
  },
  "exclude": [
    "node_modules",
    "typings/main.d.ts",
    "typings/main"
  ],
  "filesGlob": [
    "./src/**/*.ts",
    "./test/**/*.ts",
    "!./node_modules/**/*.ts",
    "src/custom-typings.d.ts",
    "typings/browser.d.ts"
  ],
  "awesomeTypescriptLoaderOptions": {
    "resolveGlobs": true,
    "forkChecker": true
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": { "rewriteTsconfig": false }
}

```

**Comment by webdev48** [comment]
So this time I tried using it on my most simplest component,

```
import {ToasterContainerComponent, ToasterService, ToasterConfig} from 'angular2-toaster/angular2-toaster';
import {Component} from 'angular2/core';
import {FORM_DIRECTIVES} from 'angular2/common';
import {bootstrap} from 'angular2/platform/browser'


@Component({

  selector: 'main-header',  // <home></home>
  providers: [ToasterService
  ],
  directives: [
    ...FORM_DIRECTIVES,ToasterContainerComponent
  ],
  pipes: [ ],
  styles: [`
  `
  ],
  template: require('./header.html')
})
export class MainHeader {
  // Set our default values
  data = { value: '' };
  logo = "assets/img/logo.png";

  userPic = "assets/img/avatars/sunny.png";

  // TypeScript public modifiers
  constructor(public toasterService: ToasterService) {

  }

  ngAfterViewInit() {
    this.toasterService.pop('success', 'Args Title', 'Args Body');
  }

}
```

**Comment by webdev48** [comment]
Please let me know if you can spot or suggest anything.

**Comment by afirdousi** [comment]
@Stabzs Have you tried using it with webpack ? The example you have given uses System JS but when I try to compile it down with webpack it doesn't work and shows me the exact same error.

Stacktrace

```
EXCEPTION: No Directive annotation found on ToasterContainerComponent
?d41d:73 Error: Uncaught (in promise): No Directive annotation found on ToasterContainerComponent
    at resolvePromise (eval at <anonymous> (polyfills.bundle.js:1153), <anonymous>:383:31)
    at eval (eval at <anonymous> (polyfills.bundle.js:1153), <anonymous>:419:17)
    at ZoneDelegate.invokeTask (eval at <anonymous> (polyfills.bundle.js:1153), <anonymous>:204:37)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (eval at <anonymous> (vendor.bundle.js:1336), <anonymous>:35:41)
    at ZoneDelegate.invokeTask (eval at <anonymous> (polyfills.bundle.js:1153), <anonymous>:203:42)
    at Zone.runTask (eval at <anonymous> (polyfills.bundle.js:1153), <anonymous>:103:47)
    at drainMicroTaskQueue (eval at <anonymous> (polyfills.bundle.js:1153), <anonymous>:322:35)
    at HTMLDocument.ZoneTask.invoke (eval at <anonymous> (polyfills.bundle.js:1153), <anonymous>:274:21)
zone.ts Unhandled Promise rejection: No Directive annotation found on ToasterContainerComponent ; Zone: angular ; Task: Promise.then ; Value:
```

**Comment by afirdousi** [comment]
My tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true
  },
  "exclude": [
    "node_modules",
    "typings/main.d.ts",
    "typings/main"
  ],
  "filesGlob": [
    "./src/**/*.ts",
    "./test/**/*.ts",
    "!./node_modules/**/*.ts",
    "src/custom-typings.d.ts",
    "typings/browser.d.ts"
  ],
  "awesomeTypescriptLoaderOptions": {
    "resolveGlobs": true,
    "forkChecker": true
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": { "rewriteTsconfig": false }
}
```

**Comment by afirdousi** [comment]
So this time I tried using it on my most simplest component,

```
import {ToasterContainerComponent, ToasterService, ToasterConfig} from 'angular2-toaster/angular2-toaster';
import {Component} from 'angular2/core';
import {FORM_DIRECTIVES} from 'angular2/common';
import {bootstrap} from 'angular2/platform/browser'


@Component({

  selector: 'main-header',  // <home></home>
  providers: [ToasterService
  ],
  directives: [
    ...FORM_DIRECTIVES,ToasterContainerComponent
  ],
  pipes: [ ],
  styles: [`
  `
  ],
  template: require('./header.html')
})
export class MainHeader {
  // Set our default values
  data = { value: '' };
  logo = "assets/img/logo.png";

  userPic = "assets/img/avatars/sunny.png";

  // TypeScript public modifiers
  constructor(public toasterService: ToasterService) {

  }

  ngAfterViewInit() {
    this.toasterService.pop('success', 'Args Title', 'Args Body');
  }

}
```

**Comment by afirdousi** [comment]
Please let me know if you can spot or suggest anything. I am looking into what webpack is generating but there is something there.

**Comment by Stabzs** [comment]
I haven't built a webpack sample yet and there very well could be an issue that is webpack related.  I will try to work on a webpack sample and see if I can't get something working for you.

**Comment by Stabzs** [comment]
I've added a webpack example.  Turned out there are a few issues/tricks with the current angular build that make things tricky.

In your root, make CERTAIN that you include `import 'angular2/bundles/angular2-polyfills';`.  If you do NOT, decorators will not be usable and you'll receive an error as such.

This doesn't expressly solve your particular error, but I wasn't able to reproduce it.  Please look at the sample I've added.  I hope it'll help give some clarity.

As a footnote, I didn't bother adding in a new package to auto-include CSS as well.  That would be a downstream effort after CSS is either inlined to components or build via scss/sass.
