### ISSUE TITLE
this._addToast observer is not defined

### ISSUE THREAD

**Issue by louie-succio** [Stabzs/Angular2-Toaster#80]
Hi,

Just to preface this, the project I'm using angular2-toaster for uses rxjs 5.0.0-beta.12 and is Angular2.1.xl.  

I'm trying to use the toasterService method .pop() with a Toast object passed in, and when I get to this check:
```
if (!this._addToast) {
            throw new Error("No Toaster Containers have been initialized to receive toasts.");
}
```
this._addToast is always undefined.

At this point in the execution of the .pop() method, the 'this' context has addToast as a property but not _addToast.  It also seems that _clearToasts is undefined as well.

I pass in a toasterConfig object to the toaster-container component with all the required fields and the Toast object I'm trying to pop has the type of 'success' and some of the optional fields filled out.

Is this a known issue? Or am I just using angular2-toaster incorrectly?

Thanks.

**Comment by Stabzs** [comment]
You are almost certainly using the library incorrectly. 

Where have you included a toaster container instance?  Can you include a simple plunker that demonstrates the issue?
