### ISSUE TITLE
Error with Angular 2 AOT

### ISSUE THREAD

**Issue by quiringk** [Stabzs/Angular2-Toaster#81]
After following all of the steps in the AOT tutorial and fixing all the issues, now at the rollup part I get the following error:

'ToasterService' is not exported by node_modules\angular2-toaster\angular2-toaster.js (imported by app\app\core\core.module.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

I am new to Angular AOT so this might not be directly a Angular2-Toaster error, just thought I'd throw this up here for now and see if anyone has any advice. I'm currently stuck at this point.

**Comment by Stabzs** [comment]
This is odd.  The service is exported (and always has been) by angular2-toaster.js:

`exports.ToasterService = require('./lib/toaster.service').ToasterService;`

Just to clarify, which version of the library are you using?

**Comment by quiringk** [comment]
1.0.2

**Comment by quiringk** [comment]
Could this be the issue?

From Angular AOT Rollup Tutorial:

"Rollup can only Tree Shake ES2015 modules which have import and export statements.

Recall that tsconfig-aot.json is configured to produce ES2015 modules. It's not important that the code itself be written with ES2015 syntax such as class and const. What matters is that the code uses ES import and export statements rather than require statements."

**Comment by Stabzs** [comment]
There's certainly an easy way to check.  If you import the service file directly, does it still throw an error?

`import { ToasterService } from './angular2-toaster/lib/toaster.service';`

Keep in mind this may be more consistent with Tree Shaking expectations.

**Comment by quiringk** [comment]
Same error after I imported directly unfortunately.

**Comment by Stabzs** [comment]
Are you able to create a small repo or fiddle reproducing the issue by chance?  I'd like to take a closer look.

**Comment by quiringk** [comment]
I figured it out. I had to do add configure the rollup-config.js file for some of my external libraries in the commonjs section. Had to include the library.

commonjs({
include: ['node_modules/rxjs/', 'node_modules/angular2-toaster/'],
})

**Comment by Stabzs** [comment]
@quiringk glad to hear it!
