### ISSUE TITLE
Prevent toast disappearing on mouseover?

### ISSUE THREAD

**Issue by AndyMeps** [Stabzs/Angular2-Toaster#83]
Would it be possible to prevent a toast from disappearing whilst the cursor is over it? Had a look at the current documentation and this doesn't seem to be implemented currently.

Thanks,

Andy

**Comment by Stabzs** [comment]
This is currently not implemented but would be a good (and consistent) feature that is in line with other, similar libraries.

**Comment by werts** [comment]
@Stabzs  Anything done?I faced with the same issue,thx anyway.

**Comment by Stabzs** [comment]
@werts yes the fix was added and the documentation was updated 10 months ago. If you are experiencing the same behavior, please add a plunker reproducing the problem and I will be happy to take a look.

**Comment by werts** [comment]
@Stabzs thx ,i have done this now

**Comment by Stabzs** [comment]
@werts I don't see a plunker.
