### ISSUE TITLE
Problem with calling toaster in observable 'subscribe'

### ISSUE THREAD

**Issue by pavlokitdev** [Stabzs/Angular2-Toaster#86]
Hi! I'm using Angular2-Toaster in Meteor+Angular2 application.
Also I'm working with Mongo collection via MongoObservable (meteor-rxjs)

I have a problem with displaying notifications after updating user profile, some time it shows after 3-4 attempt.

Here is my code:
(console.log works after each update)
    Users.update(Meteor.userId(), {
      $set: {
        'profile.first_name': data.first_name,
        'profile.last_name':  data.last_name,
        'profile.country':    data.country,
        'profile.city':       data.city,
        'profile.phone':      data.phone
      }
    })
    .subscribe(function(){
      console.log('Updated!');
      toaster.pop('success', 'Well done!', 'Profile updated');
    });

Do you have any ideas on that?

Thanks!

**Comment by Stabzs** [comment]
Can you please provide a repo?  the toast.component will explicitly force change detection for the component on toast add so that you do not have to worry about parent change detection impacting the toast container instance.

There is a possibility that your observable is not hot, causing the first few fires to not hit your subscribe properly.  If you are able to create a plunker that demonstrates the problem, it would be much easier to point you in the right direction.

**Comment by iwebd** [comment]
I have the same problem..

**Comment by Stabzs** [comment]
@iwebd if you create a plunker reproducing the issue you're seeing I'm happy to take a look

**Comment by krustypop** [comment]
Hi,
i have the same issue. When pop method is used in an observable subscribe, the toaster does not show. It perfectly works when i use it out of this context.
The shitty workaround i made is to simulate click... sadness :(
I just want to display a toaster if my POST req is a success.

If you have any tips !

Thks a lot buddy and thks for your work :)

**Comment by Stabzs** [comment]
@krustypop sorry to hear you're experiencing the same thing. Would you be able to put together a small reproduction so that I can investigate?

**Comment by krustypop** [comment]
Here it is @Stabzs 

`
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CityService } from '../../services/city.service';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';
import { ToasterService } from 'angular2-toaster';
import { Observable } from 'rxjs';
import { City } from '../../models/city';

@Component({
  selector: 'app-modal',
  template: `
    <div class="modal-body">
        <button class="btn btn-warning" (click)="toastAsync()">toastAsync</button>
        <button class="btn btn-complete" (click)="toastSync()">toastSync</button>
    </div>
  `
})
export class ModalComponent {

    constructor(public activeModal: NgbActiveModal, private toaster: ToasterService, private cityService: CityService) {}
    
    toastSync() {
        this.toaster.pop('success', 'City created with success');
    }

    toastAsync() {
        const city: City = Object.assign({}, {name: 'My Lovely City'});
        this.cityService
            .create(city)
            .map(re => re['data'])
            .subscribe(city => {
                this.toaster.pop('success', 'City created with success');
            });
    }

}

`

Maybe it comes from the fact that the toast is asked in a modal (ng-bootstrap) context ?

Thks a lot ;)
