### ISSUE TITLE
Angular 2.3 peer dependency issue

### ISSUE THREAD

**Issue by CaselIT** [Stabzs/Angular2-Toaster#88]
Hi,
Angular 2.3 updated the peer dependency of rxjs to version 5.0.0-rc.4, while this library still list it as beta.12 causing npm to complain. Please consider updating it.
Thanks

**Comment by Stabzs** [comment]
This is a duplicate of https://github.com/Stabzs/Angular2-Toaster/issues/87.  I don't want to create an additional release just for increasing the peer dependency version, especially when it can still be used successfully.  I will update the peer dependency versions to latest angular 2 and rxjs versions on the next minor release of angular2-toaster.

**Comment by CaselIT** [comment]
Did not check among the closed bug list. 
Maybe leave one the original issue open until its fixed, so it's more visible?

Sorry for the duplicate

**Comment by Stabzs** [comment]
No problem and great point.  I've reopened the original issue with a clearer title.  Thanks.
