### ISSUE TITLE
Zone.js exception

### ISSUE THREAD

**Issue by mikebm** [Stabzs/Angular2-Toaster#9]
When using angular2-toaster with the latest version of angular 2 and zone.js, an exception is thrown when removeToast() is called in the callback of the SetTimeout() function. The reason is because removeToast is calling clearTimeout which the timeout is no longer registered because it already expired.

I resolved this by changing:
 toast.timeoutId = window.setTimeout(() => {
                this.removeToast(toast);
            }, timeout);

to:
 toast.timeoutId = window.setTimeout(() => {
                toast.timeoutId = null;
                this.removeToast(toast);
            }, timeout);

**Comment by Stabzs** [comment]
This was an issue with zone.js, not the library.  This is properly fixed in zone.js 0.6.11 and https://github.com/Stabzs/Angular2-Toaster/commit/e83179e37c73a19cee019e72d90074fcf4862d27 addresses it.
