### ISSUE TITLE
BodyOutputType.Component not working

### ISSUE THREAD

**Issue by Ibrahim-Islam** [Stabzs/Angular2-Toaster#91]
See the error console message here: http://plnkr.co/edit/picmkmZhsnVxg7hicc2q?p=info

**Comment by Stabzs** [comment]
Your component is not wrapped or included in an NgModule.  Angular no longer allows you to render orphaned components dynamically.  You need to wrap your component in a module as demonstrated by the tests: https://github.com/Stabzs/Angular2-Toaster/blob/master/src/toaster-container.component.spec.ts#L41

**Comment by Stabzs** [comment]
I've updated your plunker with a working example: http://plnkr.co/edit/xn4sZkrf6dCeHwLHMlCV?p=preview
