### ISSUE TITLE
Error Loading

### ISSUE THREAD

**Issue by igordeoliveirasa** [Stabzs/Angular2-Toaster#92]
All of my 3rd libraries have been loaded successfully, however, angular2-toaster not. I've been facing with this error: 

Error loading http://localhost:3002/node_modules/angular2-toaster/angular2-toaster.js as "angular2-toaster" from http://localhost:3002/src/app/modules/index.js

This is my systemjs config:

/**
 * System configuration for Angular 2 samples
 * Adjust as necessary for your application needs.
 */
(function(global) {
    System.config({
        paths: {
            'npm:': 'node_modules/'
        },
        map: {
            // root
            'app':                        'src', // 'dist',

            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
            '@angular/upgrade': 'npm:@angular/upgrade/bundles/upgrade.umd.js',

            // vendors
            'ng2-tag-input':              'npm:ng2-tag-input',
            'rxjs':                       'npm:rxjs',
            'lodash':                     'npm:lodash',
            'jquery':                        'npm:jquery/dist',
            'bootstrap':                        'npm:bootstrap/dist/js',
            'pluralize':                              'npm:pluralize',
            'angular2-text-mask':                     'npm:angular2-text-mask/dist',
            'ng2-select':                     'npm:ng2-select',
            'angular2-infinite-scroll':                     'npm:angular2-infinite-scroll',
            'angular2-google-maps':                         'npm:angular2-google-maps',
            'ng2-currency-mask':                         'npm:ng2-currency-mask',
            'socket.io-client':                         'npm:socket.io-client/dist',
            'ng2-datetime':                         'npm:ng2-datetime',
            'angular2-toaster':                     'npm:angular2-toaster'
        },
        packages: {
            'app':                        { main: 'main.js',  defaultExtension: 'js' },
            'rxjs':                       { defaultExtension: 'js' },
            'ng2-tag-input':              { main: 'index.js', defaultExtension: 'js' },
            'lodash':                     {main: 'index.js', defaultExtension: 'js'},
            'jquery':                     {main: 'jquery.min.js', defaultExtension: 'js'},
            'bootstrap':                     {main: 'bootstrap.min.js', defaultExtension: 'js'},
            'pluralize':                     {main: 'pluralize.js', defaultExtension: 'js'},
            'angular2-text-mask':                     {main: 'angular2TextMask.js', defaultExtension: 'js'},
            'ng2-select':                     {main: 'ng2-select.js', defaultExtension: 'js'},
            'angular2-infinite-scroll':                     {main: 'angular2-infinite-scroll.js', defaultExtension: 'js'},
            'angular2-google-maps/core': {main: 'index.js', defaultExtension: 'js'},
            'ng2-currency-mask': {main: 'index.js', defaultExtension: 'js'},
            'socket.io-client': {main: 'socket.io.js', defaultExtension: 'js'},
            'ng2-datetime': {main: 'ng2-datetime.js', defaultExtension: 'js'},
            'angular2-toaster':                     {main: 'angular2-toaster.js', defaultExtension: 'js'},
        }
    });
})(this);

**Comment by Stabzs** [comment]
If using the umd format (which it appears you are), you would want to update your mapping to hit the umd file instead and forego the package mapping:

`'angular2-toaster': 'npm:angular2-toaster/bundles/angular2-toaster.umd.js'

This requires version 2.1.0.
