### ISSUE TITLE
Incomplete Information for Importing with SystemJS

### ISSUE THREAD

**Issue by dhyey35** [Stabzs/Angular2-Toaster#93]
I think the Readme.md file should have the following information for importing angular2-toaster files with default configuration from angular2 quickstart using systemJS.

In  your systemjs.config.js file include angular2-toaster by adding it in map object:

```javascript
// other libraries
      'rxjs':                      'npm:rxjs',
      'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
      'angular2-toaster':          'npm:angular2-toaster/bundles/angular2-toaster.umd.js'
    },
```

Also documentation does not mention the use of **animationClass** in ToasterConfig.

Should I submit a PR ?

**Comment by Stabzs** [comment]
Absolutely agreed, this would be very useful information. I'll add it to the documentation.
