### ISSUE TITLE
animationClass 'toast-bottom-right' and 'toast-bottom-center' not working

### ISSUE THREAD

**Issue by dhyey35** [Stabzs/Angular2-Toaster#94]
![screenshot from 2017-01-09 16-15-29](https://cloud.githubusercontent.com/assets/11143604/21764014/eafaa016-d686-11e6-91d9-7831f95a6e10.png)

The 'toast-bottom-right' and 'toast-bottom-centrer' both classes need **top:auto** property to avoid top:12px being set by 'toast-top-right' class.

Would love to submit a PR.

**Comment by Stabzs** [comment]
animations are not yet added to the library.  This is a future enhancement.

**Comment by Stabzs** [comment]
Closing since this is probably an improper use of the positionClass.
