### ISSUE TITLE
Animation example

### ISSUE THREAD

**Issue by EvaldasVasiliauskas** [Stabzs/Angular2-Toaster#95]
Could you please provide an example of how one could add animations to toast container. I see that animationClass property is exposed, but for example if I set it to "fade" toast contained becomes invisible...

Or is animations not yet implemented? 

Many thanks for great lib.

**Comment by Stabzs** [comment]
Thank you for the feedback!

Animations are not yet added.  They are a future enhancement and will be added in the near future.
