### ISSUE TITLE
How to serve the cloned repo in local? (Help Wanted) 

### ISSUE THREAD

**Issue by anvesh48** [Stabzs/Angular2-Toaster#96]
I am trying to work on the progessBar feature. Can you please help me how to serve the application in my localhost:

I did below things:
git clone https://github.com/stabzs/Angular2-Toaster.git
npm install
npm start (not shows the port number to direct to).

Can you please help how to run the application in localhost?

**Comment by Stabzs** [comment]
Thank you for taking a look at the progress bar feature!  I haven't had time to get to it.

It will serve up source, not a full application, on http://127.0.0.1:8875.  To aid in development, it would probably be beneficial to create a bootstrapped source "project" that makes it easier.  If I can get to creating a full-blown demo site, it would be ideal to loop that into the dev process, but it doesn't exist yet.

**Comment by anvesh48** [comment]
You are welcome and that's fine with me.
