### ISSUE TITLE
Error in multistyles Module not found

### ISSUE THREAD

**Issue by anvesh48** [Stabzs/Angular2-Toaster#97]
ERROR in multi styles                                                                                                                                                                 
Module not found: Error: Can't resolve '\test\node_modules\angular2-toaster\lib\toaster.css' in '\project-all\test'                                                                                                                                   
 @ multi styles   

Also in the browser console:
Uncaught Error: Cannot find module "\test\node_modules\angular2-toaster\lib\toaster.css"

I am updating my angular project and all the plugins to the latest version and when i am serving the application i am seeing the above errors in the console.

**Comment by Stabzs** [comment]
Correct, the toaster.css file no longer lives in the lib folder in `2.0.0`, since the library was updated to follow the umd spec.  It is now available under the package root, or `/node_modules/angular2-toaster/toaster.css`.

**Comment by anvesh48** [comment]
Got you..! Thanks :)
