### ISSUE TITLE
No Toaster Containers have been initialized to receive toasts

### ISSUE THREAD

**Issue by andrejkaurin** [Stabzs/Angular2-Toaster#98]
```
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    ToasterModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {
}
```

```
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  
}
```

```
<div class="page-container">
  <div class="content-wrapper">
    <router-outlet></router-outlet>
    <toaster-container></toaster-container>
  </div>
</div>

```

Then injecting ToasterService and calling
`this.toasterService.pop('success', 'Some message');`

**Comment by Stabzs** [comment]
How are you actually rendering your app component?  Is it bootstrapped correctly?

Please create a plunker demonstrating the issue and I'll be happy to take a look.

**Comment by robinkedia** [comment]
I get this too in NgOninit() for pop but not for popAsync

**Comment by Stabzs** [comment]
@robinkedia you shouldn't be invoking the toaster service in NgOnInit since it is too early in the component lifecycle.  The reason it works for popAsync is because it lives outside of the lifecycle and most likely is firing after the component is fully rendered.

**Comment by girishbalanagu** [comment]
Is there any way to display toastr after the ngOninit() method.

**Comment by Stabzs** [comment]
@girishbalanagu absolutely, there are other lifecycle hooks that you can (and should) use instead.  Look at the [After View](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#afterview) part of the lifecycle.

**Comment by korayguclu** [comment]
How can i call the popup in error handler. I am getting the same error

`import { ToasterService, Toast } from 'angular2-toaster';
@Injectable()
export class AppErrorHandler implements ErrorHandler {
  constructor(private injector: Injector) {
  }

  handleError(error) {
    const toasterService = this.injector.get(ToasterService);
    let toast: Toast = { 
      type: 'error', data: 1, 
      onHideCallback: (toast) => console.log(toast.data) };
    toasterService.pop(toast);

    console.log('GLOBAL', error);
    throw error;
  }

}
`
