### ISSUE TITLE
Unhandled Promise rejection: ctorParameters.map is not a function

### ISSUE THREAD

**Issue by OvidiuBan** [Stabzs/Angular2-Toaster#99]
Getting this after adding angular2-toaster.

**Comment by Stabzs** [comment]
map() is not used in angular2-toaster so you most likely did not properly import map in your consuming code. Please create a plunker demonstrating the issue and I'll be happy to take a look.

**Comment by OvidiuBan** [comment]
@Stabzs Sorry mate, this can be closed, this was an issue of trying to use Angular2-toaster with old in memory api / angular 2.1 . Works great
